In [13]:
checkpoint = "prajjwal1/bert-tiny"
tokenizer_checkpoint = "bert-base-uncased"
dataset_name = "imdb"

from transformers import AutoModel

model = AutoModel.from_pretrained(checkpoint)

from chop.tools import get_tokenized_dataset

dataset, tokenizer = get_tokenized_dataset(
    dataset=dataset_name,
    checkpoint=tokenizer_checkpoint,
    return_tokenizer=True,
)

from pathlib import Path
import dill

with open(f"{Path.home()}/tutorial_5_best_model.pkl", "rb") as f:
    base_model = dill.load(f)

INFO     Tokenizing dataset imdb with AutoTokenizer for bert-base-uncased.

# Task 1

In Tutorial 6, all layers allocated to IntegerLinear are allocated the same width and fractional width. This is suboptimal, as different layers may have different sensitivities to quantization.

-    Modify the code to allow different layers to have widths in the range [8, 16, 32] and fractional widths in the range [2, 4, 8]. Expose this choice as an additional hyperparameter for the Optuna sampler.

-    Run the search again, and plot a figure that has the number of trials on the x axis, and the maximum achieved accuracy up to that point on the y axis.

## Extended Precision Search

This notebook extends the original search to include **all supported precision types** for Linear layers in MASE:

### Supported Precision Types:
1. **float32** - Full precision (baseline)
2. **integer** - Fixed-point integer quantization with configurable width and fractional bits
3. **minifloat_denorm** - Minifloat with denormalized representation
4. **minifloat_ieee** - IEEE-compliant minifloat format
5. **log** - Logarithmic quantization
6. **block_fp** - Block floating point with shared exponents
7. **block_minifloat** - Block minifloat quantization
8. **block_log** - Block logarithmic quantization
9. **binary** - Binary neural networks (1-bit weights)
10. **binary_scaling** - Binary with scaling factors

### Search Space Parameters:
- **Integer**: width ∈ {8, 16, 32}, frac_width ∈ {2, 4, 8}
- **Minifloat**: width ∈ {8, 16}, exponent_width ∈ {3, 4, 5}, exponent_bias ∈ {7, 15}
- **Log**: width ∈ {4, 8}
- **Block-based**: block_size ∈ {8, 16, 32}
- **Binary**: stochastic ∈ {True, False}, bipolar ∈ {True, False}

### Methodology:
1. Run separate Optuna studies for each precision type
2. Each study optimizes layer-specific hyperparameters
3. Compare cumulative maximum accuracy across trials
4. Visualize and analyze results

In [14]:
# Defining Search Space with Working Precision Types

import torch
from chop.nn.quantized.modules.linear import (
    LinearInteger,
    LinearMinifloatDenorm,
    LinearMinifloatIEEE,
    LinearLog,
    LinearBinary,
    LinearBinaryScaling,
)

# ============================================================================
# PRECISION TYPE DEFINITIONS
# Only include precision types that have working gradient implementations
# ============================================================================

PRECISION_TYPES = {
    "float32": {
        "class": torch.nn.Linear,
        "config_generator": None,  # No config needed for full precision
    },
    "integer": {
        "class": LinearInteger,
        "config_generator": lambda trial, name, search_space: {
            "data_in_width": trial.suggest_categorical(f"{name}_int_width", search_space["int_width"]),
            "data_in_frac_width": trial.suggest_categorical(f"{name}_int_frac_width", search_space["frac_width"]),
            "weight_width": trial.suggest_categorical(f"{name}_weight_width", search_space["int_width"]),
            "weight_frac_width": trial.suggest_categorical(f"{name}_weight_frac_width", search_space["frac_width"]),
            "bias_width": trial.suggest_categorical(f"{name}_bias_width", search_space["int_width"]),
            "bias_frac_width": trial.suggest_categorical(f"{name}_bias_frac_width", search_space["frac_width"]),
        },
    },
    "minifloat_denorm": {
        "class": LinearMinifloatDenorm,
        "config_generator": lambda trial, name, search_space: {
            "data_in_width": trial.suggest_categorical(f"{name}_mfd_width", search_space["minifloat_width"]),
            "data_in_exponent_width": trial.suggest_categorical(f"{name}_mfd_exp_width", search_space["exponent_width"]),
            "data_in_exponent_bias": trial.suggest_categorical(f"{name}_mfd_exp_bias", search_space["exponent_bias"]),
            "weight_width": trial.suggest_categorical(f"{name}_mfd_w_width", search_space["minifloat_width"]),
            "weight_exponent_width": trial.suggest_categorical(f"{name}_mfd_w_exp_width", search_space["exponent_width"]),
            "weight_exponent_bias": trial.suggest_categorical(f"{name}_mfd_w_exp_bias", search_space["exponent_bias"]),
            "bias_width": trial.suggest_categorical(f"{name}_mfd_b_width", search_space["minifloat_width"]),
            "bias_exponent_width": trial.suggest_categorical(f"{name}_mfd_b_exp_width", search_space["exponent_width"]),
            "bias_exponent_bias": trial.suggest_categorical(f"{name}_mfd_b_exp_bias", search_space["exponent_bias"]),
        },
    },
    "minifloat_ieee": {
        "class": LinearMinifloatIEEE,
        "config_generator": lambda trial, name, search_space: {
            "data_in_width": trial.suggest_categorical(f"{name}_mfi_width", search_space["minifloat_width"]),
            "data_in_exponent_width": trial.suggest_categorical(f"{name}_mfi_exp_width", search_space["exponent_width"]),
            "data_in_exponent_bias": trial.suggest_categorical(f"{name}_mfi_exp_bias", search_space["exponent_bias"]),
            "weight_width": trial.suggest_categorical(f"{name}_mfi_w_width", search_space["minifloat_width"]),
            "weight_exponent_width": trial.suggest_categorical(f"{name}_mfi_w_exp_width", search_space["exponent_width"]),
            "weight_exponent_bias": trial.suggest_categorical(f"{name}_mfi_w_exp_bias", search_space["exponent_bias"]),
            "bias_width": trial.suggest_categorical(f"{name}_mfi_b_width", search_space["minifloat_width"]),
            "bias_exponent_width": trial.suggest_categorical(f"{name}_mfi_b_exp_width", search_space["exponent_width"]),
            "bias_exponent_bias": trial.suggest_categorical(f"{name}_mfi_b_exp_bias", search_space["exponent_bias"]),
        },
    },
    "log": {
        "class": LinearLog,
        "config_generator": lambda trial, name, search_space: {
            "data_in_width": trial.suggest_categorical(f"{name}_log_width", search_space["log_width"]),
            "data_in_exponent_bias": trial.suggest_categorical(f"{name}_log_exp_bias", search_space["exponent_bias"]),
            "weight_width": trial.suggest_categorical(f"{name}_log_w_width", search_space["log_width"]),
            "weight_exponent_bias": trial.suggest_categorical(f"{name}_log_w_exp_bias", search_space["exponent_bias"]),
            "bias_width": trial.suggest_categorical(f"{name}_log_b_width", search_space["log_width"]),
            "bias_exponent_bias": trial.suggest_categorical(f"{name}_log_b_exp_bias", search_space["exponent_bias"]),
        },
    },
    "binary": {
        "class": LinearBinary,
        "config_generator": lambda trial, name, search_space: {
            "weight_stochastic": trial.suggest_categorical(f"{name}_bin_w_stochastic", [True, False]),
            "weight_bipolar": trial.suggest_categorical(f"{name}_bin_w_bipolar", [True, False]),
        },
    },
    "binary_scaling": {
        "class": LinearBinaryScaling,
        "config_generator": lambda trial, name, search_space: {
            "data_in_stochastic": trial.suggest_categorical(f"{name}_bins_x_stochastic", [True, False]),
            "data_in_bipolar": trial.suggest_categorical(f"{name}_bins_x_bipolar", [True, False]),
            "weight_stochastic": trial.suggest_categorical(f"{name}_bins_w_stochastic", [True, False]),
            "weight_bipolar": trial.suggest_categorical(f"{name}_bins_w_bipolar", [True, False]),
            "bias_stochastic": trial.suggest_categorical(f"{name}_bins_b_stochastic", [True, False]),
            "bias_bipolar": trial.suggest_categorical(f"{name}_bins_b_bipolar", [True, False]),
            "binary_training": True,  # Always enable binary training for search
        },
    },
}

# ============================================================================
# SEARCH SPACE DEFINITION
# Defines the hyperparameter ranges for each precision type
# ============================================================================

search_space = {
    # Integer quantization parameters
    "int_width": [8, 16, 32],
    "frac_width": [2, 4, 8],
    
    # Minifloat parameters (for denorm, IEEE)
    "minifloat_width": [8, 16],
    "exponent_width": [3, 4, 5],
    "exponent_bias": [7, 15],
    
    # Log quantization parameters
    "log_width": [4, 8],
    
    # Available precision types for layer selection
    "precision_types": list(PRECISION_TYPES.keys()),
}

# ============================================================================
# MODEL CONSTRUCTOR
# Creates a model with layers quantized according to Optuna suggestions
# ============================================================================

from chop.tools.utils import deepsetattr
from copy import deepcopy


def construct_model(trial, precision_type=None):
    """
    Construct a model with quantized layers based on Optuna trial suggestions.
    
    Args:
        trial: Optuna trial object for hyperparameter suggestions
        precision_type: If specified, use this precision type for all layers.
                       If None, let Optuna choose per-layer precision.
    
    Returns:
        A copy of base_model with layers replaced according to precision choices
    """
    trial_model = deepcopy(base_model)
    
    for name, layer in trial_model.named_modules():
        if isinstance(layer, torch.nn.Linear):
            # Determine the precision type for this layer
            if precision_type is not None:
                # Use the specified precision type for all layers
                chosen_precision = precision_type
            else:
                # Let Optuna choose the precision type per layer
                chosen_precision = trial.suggest_categorical(
                    f"{name}_precision_type",
                    search_space["precision_types"],
                )
            
            precision_info = PRECISION_TYPES[chosen_precision]
            new_layer_cls = precision_info["class"]
            
            # Skip if full precision (torch.nn.Linear)
            if new_layer_cls == torch.nn.Linear:
                continue
            
            # Build keyword arguments for the new layer
            kwargs = {
                "in_features": layer.in_features,
                "out_features": layer.out_features,
                "bias": layer.bias is not None,
            }
            
            # Generate config using the precision-specific config generator
            config_generator = precision_info["config_generator"]
            if config_generator is not None:
                kwargs["config"] = config_generator(trial, name, search_space)
            
            # Create the new layer and copy weights
            new_layer = new_layer_cls(**kwargs)
            new_layer.weight.data = layer.weight.data.clone()
            if layer.bias is not None and new_layer.bias is not None:
                new_layer.bias.data = layer.bias.data.clone()
            
            # Replace the layer in the model
            deepsetattr(trial_model, name, new_layer)
    
    return trial_model


print("✓ Search space defined with", len(PRECISION_TYPES), "precision types:")
for name in PRECISION_TYPES:
    print(f"  - {name}: {PRECISION_TYPES[name]['class'].__name__}")
print("\nNote: Block-based quantizers (BlockFP, BlockMinifloat, BlockLog) removed due to gradient issues.")

✓ Search space defined with 7 precision types:
  - float32: Linear
  - integer: LinearInteger
  - minifloat_denorm: LinearMinifloatDenorm
  - minifloat_ieee: LinearMinifloatIEEE
  - log: LinearLog
  - binary: LinearBinary
  - binary_scaling: LinearBinaryScaling

Note: Block-based quantizers (BlockFP, BlockMinifloat, BlockLog) removed due to gradient issues.

In [15]:
# Print search space summary
print("=" * 60)
print("SEARCH SPACE SUMMARY")
print("=" * 60)
for key, values in search_space.items():
    print(f"{key}: {values}")

============================================================
SEARCH SPACE SUMMARY
============================================================
int_width: [8, 16, 32]
frac_width: [2, 4, 8]
minifloat_width: [8, 16]
exponent_width: [3, 4, 5]
exponent_bias: [7, 15]
log_width: [4, 8]
precision_types: ['float32', 'integer', 'minifloat_denorm', 'minifloat_ieee', 'log', 'binary', 'binary_scaling']

In [16]:
# ============================================================================
# STUDY CONFIGURATION
# Configuration for running precision-specific studies
# ============================================================================

from optuna.samplers import GridSampler, RandomSampler, TPESampler

sampler = RandomSampler()

In [17]:
from chop.tools import get_trainer
import traceback


def objective(trial):
    try:
        # Define the model
        model = construct_model(trial)

        trainer = get_trainer(
            model=model,
            tokenized_dataset=dataset,
            tokenizer=tokenizer,
            evaluate_metric="accuracy",
            num_train_epochs=1,
        )

        trainer.train()
        eval_results = trainer.evaluate()

        # Store precision type used
        precision_used = trial.params.get(f"{list(trial.params.keys())[0].split('_precision_type')[0]}_precision_type", "unknown")
        trial.set_user_attr("model", model)
        trial.set_user_attr("precision_type", precision_used)

        return eval_results["eval_accuracy"]
    
    except Exception as e:
        # Log the error and return 0.0 for failed trials
        print(f"Trial {trial.number} failed with error: {str(e)}")
        traceback.print_exc()
        return 0.0

In [ ]:
import optuna

study = optuna.create_study(
    direction="maximize",
    study_name="bert-tiny-nas-study",
    sampler=sampler,
)

study.optimize(
    objective,
    n_trials=50,  # Run 50 trials to test different precision types
    timeout=60 * 60 * 24,
)

[I 2026-02-03 13:46:14,244] A new study created in memory with name: bert-tiny-nas-study
/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 627, in forward
    layer_output = apply_chunking_to_forward(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/pytorch_utils.py", line 253, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 640, in feed_forward_chunk
    layer_output = self.output(intermediate_output, attention_output)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 552, in forward
    hidden_states = self.dense(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 446, in linearBinaryScaling
    x = x_quantizer(x)
        ^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 48, in binary_quantizer
    else binarised_zeroScaled_op(x_sig, x_rand)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
[I 2026-02-03 13:46:16,775] Trial 0 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'minifloat_ieee', 'bert.encoder.layer.0.attention.self.query_mfi_width': 16, 'bert.encoder.layer.0.attention.self.query_mfi_exp_width': 4, 'bert.encoder.layer.0.attention.self.query_mfi_exp_bias': 15, 'bert.encoder.layer.0.attention.self.query_mfi_w_width': 8, 'bert.encoder.layer.0.attention.self.query_mfi_w_exp_width': 4, 'bert.encoder.layer.0.attention.self.query_mfi_w_exp_bias': 7, 'bert.encoder.layer.0.attention.self.query_mfi_b_width': 8, 'bert.encoder.layer.0.attention.self.query_mfi_b_exp_width': 5, 'bert.encoder.layer.0.attention.self.query_mfi_b_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_precision_type': 'minifloat_ieee', 'bert.encoder.layer.0.attention.self.value_mfi_width': 8, 'bert.encoder.layer.0.attention.self.value_mfi_exp_width': 3, 'bert.encoder.layer.0.attention.self.value_mfi_exp_bias': 7, 'bert.encoder.layer.0.attention.self.value_mfi_w_width': 16, 'bert.encoder.layer.0.attention.self.value_mfi_w_exp_width': 3, 'bert.encoder.layer.0.attention.self.value_mfi_w_exp_bias': 7, 'bert.encoder.layer.0.attention.self.value_mfi_b_width': 8, 'bert.encoder.layer.0.attention.self.value_mfi_b_exp_width': 3, 'bert.encoder.layer.0.attention.self.value_mfi_b_exp_bias': 7, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'integer', 'bert.encoder.layer.0.intermediate.dense_int_width': 8, 'bert.encoder.layer.0.intermediate.dense_int_frac_width': 8, 'bert.encoder.layer.0.intermediate.dense_weight_width': 8, 'bert.encoder.layer.0.intermediate.dense_weight_frac_width': 4, 'bert.encoder.layer.0.intermediate.dense_bias_width': 32, 'bert.encoder.layer.0.intermediate.dense_bias_frac_width': 2, 'bert.encoder.layer.0.output.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.0.output.dense_bins_x_stochastic': True, 'bert.encoder.layer.0.output.dense_bins_x_bipolar': False, 'bert.encoder.layer.0.output.dense_bins_w_stochastic': False, 'bert.encoder.layer.0.output.dense_bins_w_bipolar': True, 'bert.encoder.layer.0.output.dense_bins_b_stochastic': False, 'bert.encoder.layer.0.output.dense_bins_b_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'float32', 'bert.encoder.layer.1.intermediate.dense_precision_type': 'float32', 'bert.encoder.layer.1.output.dense_precision_type': 'binary', 'bert.encoder.layer.1.output.dense_bin_w_stochastic': False, 'bert.encoder.layer.1.output.dense_bin_w_bipolar': True, 'classifier_precision_type': 'minifloat_denorm', 'classifier_mfd_width': 8, 'classifier_mfd_exp_width': 3, 'classifier_mfd_exp_bias': 7, 'classifier_mfd_w_width': 8, 'classifier_mfd_w_exp_width': 3, 'classifier_mfd_w_exp_bias': 15, 'classifier_mfd_b_width': 8, 'classifier_mfd_b_exp_width': 3, 'classifier_mfd_b_exp_bias': 15}. Best is trial 0 with value: 0.0.

Trial 0 failed with error: Dimension out of range (expected to be in range of [-3, 2], but got 3)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 585, in forward
    self_attention_outputs = self.attention(
                             ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 515, in forward
    self_outputs = self.self(
                   ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 409, in forward
    value_layer = self.transpose_for_scores(self.value(current_states))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 448, in linearBinaryScaling
    bias = b_quantizer(bias) if bias is not None else None
           ^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 48, in binary_quantizer
    else binarised_zeroScaled_op(x_sig, x_rand)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
[I 2026-02-03 13:46:17,667] Trial 1 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'log', 'bert.encoder.layer.0.attention.self.query_log_width': 4, 'bert.encoder.layer.0.attention.self.query_log_exp_bias': 15, 'bert.encoder.layer.0.attention.self.query_log_w_width': 8, 'bert.encoder.layer.0.attention.self.query_log_w_exp_bias': 7, 'bert.encoder.layer.0.attention.self.query_log_b_width': 8, 'bert.encoder.layer.0.attention.self.query_log_b_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_precision_type': 'binary_scaling', 'bert.encoder.layer.0.attention.self.value_bins_x_stochastic': False, 'bert.encoder.layer.0.attention.self.value_bins_x_bipolar': True, 'bert.encoder.layer.0.attention.self.value_bins_w_stochastic': True, 'bert.encoder.layer.0.attention.self.value_bins_w_bipolar': True, 'bert.encoder.layer.0.attention.self.value_bins_b_stochastic': True, 'bert.encoder.layer.0.attention.self.value_bins_b_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'minifloat_ieee', 'bert.encoder.layer.0.intermediate.dense_mfi_width': 8, 'bert.encoder.layer.0.intermediate.dense_mfi_exp_width': 3, 'bert.encoder.layer.0.intermediate.dense_mfi_exp_bias': 15, 'bert.encoder.layer.0.intermediate.dense_mfi_w_width': 8, 'bert.encoder.layer.0.intermediate.dense_mfi_w_exp_width': 3, 'bert.encoder.layer.0.intermediate.dense_mfi_w_exp_bias': 15, 'bert.encoder.layer.0.intermediate.dense_mfi_b_width': 8, 'bert.encoder.layer.0.intermediate.dense_mfi_b_exp_width': 5, 'bert.encoder.layer.0.intermediate.dense_mfi_b_exp_bias': 15, 'bert.encoder.layer.0.output.dense_precision_type': 'float32', 'bert.encoder.layer.1.attention.output.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.1.attention.output.dense_mfd_width': 8, 'bert.encoder.layer.1.attention.output.dense_mfd_exp_width': 4, 'bert.encoder.layer.1.attention.output.dense_mfd_exp_bias': 15, 'bert.encoder.layer.1.attention.output.dense_mfd_w_width': 16, 'bert.encoder.layer.1.attention.output.dense_mfd_w_exp_width': 3, 'bert.encoder.layer.1.attention.output.dense_mfd_w_exp_bias': 15, 'bert.encoder.layer.1.attention.output.dense_mfd_b_width': 8, 'bert.encoder.layer.1.attention.output.dense_mfd_b_exp_width': 5, 'bert.encoder.layer.1.attention.output.dense_mfd_b_exp_bias': 7, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'binary', 'bert.encoder.layer.1.intermediate.dense_bin_w_stochastic': True, 'bert.encoder.layer.1.intermediate.dense_bin_w_bipolar': True, 'bert.encoder.layer.1.output.dense_precision_type': 'log', 'bert.encoder.layer.1.output.dense_log_width': 8, 'bert.encoder.layer.1.output.dense_log_exp_bias': 7, 'bert.encoder.layer.1.output.dense_log_w_width': 4, 'bert.encoder.layer.1.output.dense_log_w_exp_bias': 15, 'bert.encoder.layer.1.output.dense_log_b_width': 8, 'bert.encoder.layer.1.output.dense_log_b_exp_bias': 7, 'classifier_precision_type': 'minifloat_ieee', 'classifier_mfi_width': 8, 'classifier_mfi_exp_width': 3, 'classifier_mfi_exp_bias': 7, 'classifier_mfi_w_width': 8, 'classifier_mfi_w_exp_width': 5, 'classifier_mfi_w_exp_bias': 15, 'classifier_mfi_b_width': 8, 'classifier_mfi_b_exp_width': 5, 'classifier_mfi_b_exp_bias': 7}. Best is trial 0 with value: 0.0.

Trial 1 failed with error: Dimension out of range (expected to be in range of [-1, 0], but got 1)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 627, in forward
    layer_output = apply_chunking_to_forward(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/pytorch_utils.py", line 253, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 640, in feed_forward_chunk
    layer_output = self.output(intermediate_output, attention_output)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 552, in forward
    hidden_states = self.dense(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 446, in linearBinaryScaling
    x = x_quantizer(x)
        ^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 51, in binary_quantizer
    x = binarised_bipolar_op(x, 0) if bipolar else binarised_zeroScaled_op(x, 0)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
[I 2026-02-03 13:46:18,762] Trial 2 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'float32', 'bert.encoder.layer.0.attention.self.value_precision_type': 'float32', 'bert.encoder.layer.0.intermediate.dense_precision_type': 'float32', 'bert.encoder.layer.0.output.dense_precision_type': 'minifloat_ieee', 'bert.encoder.layer.0.output.dense_mfi_width': 16, 'bert.encoder.layer.0.output.dense_mfi_exp_width': 4, 'bert.encoder.layer.0.output.dense_mfi_exp_bias': 15, 'bert.encoder.layer.0.output.dense_mfi_w_width': 16, 'bert.encoder.layer.0.output.dense_mfi_w_exp_width': 5, 'bert.encoder.layer.0.output.dense_mfi_w_exp_bias': 15, 'bert.encoder.layer.0.output.dense_mfi_b_width': 8, 'bert.encoder.layer.0.output.dense_mfi_b_exp_width': 4, 'bert.encoder.layer.0.output.dense_mfi_b_exp_bias': 15, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.1.attention.output.dense_mfd_width': 8, 'bert.encoder.layer.1.attention.output.dense_mfd_exp_width': 3, 'bert.encoder.layer.1.attention.output.dense_mfd_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_mfd_w_width': 16, 'bert.encoder.layer.1.attention.output.dense_mfd_w_exp_width': 3, 'bert.encoder.layer.1.attention.output.dense_mfd_w_exp_bias': 15, 'bert.encoder.layer.1.attention.output.dense_mfd_b_width': 8, 'bert.encoder.layer.1.attention.output.dense_mfd_b_exp_width': 4, 'bert.encoder.layer.1.attention.output.dense_mfd_b_exp_bias': 7, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.1.intermediate.dense_mfd_width': 16, 'bert.encoder.layer.1.intermediate.dense_mfd_exp_width': 4, 'bert.encoder.layer.1.intermediate.dense_mfd_exp_bias': 15, 'bert.encoder.layer.1.intermediate.dense_mfd_w_width': 8, 'bert.encoder.layer.1.intermediate.dense_mfd_w_exp_width': 5, 'bert.encoder.layer.1.intermediate.dense_mfd_w_exp_bias': 15, 'bert.encoder.layer.1.intermediate.dense_mfd_b_width': 8, 'bert.encoder.layer.1.intermediate.dense_mfd_b_exp_width': 3, 'bert.encoder.layer.1.intermediate.dense_mfd_b_exp_bias': 15, 'bert.encoder.layer.1.output.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.1.output.dense_bins_x_stochastic': False, 'bert.encoder.layer.1.output.dense_bins_x_bipolar': False, 'bert.encoder.layer.1.output.dense_bins_w_stochastic': True, 'bert.encoder.layer.1.output.dense_bins_w_bipolar': False, 'bert.encoder.layer.1.output.dense_bins_b_stochastic': True, 'bert.encoder.layer.1.output.dense_bins_b_bipolar': True, 'classifier_precision_type': 'log', 'classifier_log_width': 8, 'classifier_log_exp_bias': 7, 'classifier_log_w_width': 8, 'classifier_log_w_exp_bias': 15, 'classifier_log_b_width': 8, 'classifier_log_b_exp_bias': 15}. Best is trial 0 with value: 0.0.

Trial 2 failed with error: Dimension out of range (expected to be in range of [-3, 2], but got 3)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 585, in forward
    self_attention_outputs = self.attention(
                             ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 524, in forward
    attention_output = self.output(self_outputs[0], hidden_states)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 466, in forward
    hidden_states = self.dense(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 288, in forward
    return linearBinary(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 408, in linearBinary
    weight = w_quantizer(weight)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 51, in binary_quantizer
    x = binarised_bipolar_op(x, 0) if bipolar else binarised_zeroScaled_op(x, 0)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
[I 2026-02-03 13:46:19,675] Trial 3 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'log', 'bert.encoder.layer.0.attention.self.query_log_width': 4, 'bert.encoder.layer.0.attention.self.query_log_exp_bias': 7, 'bert.encoder.layer.0.attention.self.query_log_w_width': 4, 'bert.encoder.layer.0.attention.self.query_log_w_exp_bias': 7, 'bert.encoder.layer.0.attention.self.query_log_b_width': 4, 'bert.encoder.layer.0.attention.self.query_log_b_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_precision_type': 'integer', 'bert.encoder.layer.0.attention.self.value_int_width': 16, 'bert.encoder.layer.0.attention.self.value_int_frac_width': 4, 'bert.encoder.layer.0.attention.self.value_weight_width': 8, 'bert.encoder.layer.0.attention.self.value_weight_frac_width': 8, 'bert.encoder.layer.0.attention.self.value_bias_width': 32, 'bert.encoder.layer.0.attention.self.value_bias_frac_width': 8, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'integer', 'bert.encoder.layer.0.intermediate.dense_int_width': 32, 'bert.encoder.layer.0.intermediate.dense_int_frac_width': 2, 'bert.encoder.layer.0.intermediate.dense_weight_width': 8, 'bert.encoder.layer.0.intermediate.dense_weight_frac_width': 2, 'bert.encoder.layer.0.intermediate.dense_bias_width': 16, 'bert.encoder.layer.0.intermediate.dense_bias_frac_width': 4, 'bert.encoder.layer.0.output.dense_precision_type': 'integer', 'bert.encoder.layer.0.output.dense_int_width': 8, 'bert.encoder.layer.0.output.dense_int_frac_width': 4, 'bert.encoder.layer.0.output.dense_weight_width': 16, 'bert.encoder.layer.0.output.dense_weight_frac_width': 2, 'bert.encoder.layer.0.output.dense_bias_width': 32, 'bert.encoder.layer.0.output.dense_bias_frac_width': 8, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'binary', 'bert.encoder.layer.1.attention.output.dense_bin_w_stochastic': False, 'bert.encoder.layer.1.attention.output.dense_bin_w_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.1.intermediate.dense_mfd_width': 8, 'bert.encoder.layer.1.intermediate.dense_mfd_exp_width': 5, 'bert.encoder.layer.1.intermediate.dense_mfd_exp_bias': 15, 'bert.encoder.layer.1.intermediate.dense_mfd_w_width': 8, 'bert.encoder.layer.1.intermediate.dense_mfd_w_exp_width': 4, 'bert.encoder.layer.1.intermediate.dense_mfd_w_exp_bias': 15, 'bert.encoder.layer.1.intermediate.dense_mfd_b_width': 8, 'bert.encoder.layer.1.intermediate.dense_mfd_b_exp_width': 5, 'bert.encoder.layer.1.intermediate.dense_mfd_b_exp_bias': 7, 'bert.encoder.layer.1.output.dense_precision_type': 'integer', 'bert.encoder.layer.1.output.dense_int_width': 32, 'bert.encoder.layer.1.output.dense_int_frac_width': 2, 'bert.encoder.layer.1.output.dense_weight_width': 16, 'bert.encoder.layer.1.output.dense_weight_frac_width': 2, 'bert.encoder.layer.1.output.dense_bias_width': 16, 'bert.encoder.layer.1.output.dense_bias_frac_width': 8, 'classifier_precision_type': 'binary_scaling', 'classifier_bins_x_stochastic': False, 'classifier_bins_x_bipolar': False, 'classifier_bins_w_stochastic': True, 'classifier_bins_w_bipolar': False, 'classifier_bins_b_stochastic': False, 'classifier_bins_b_bipolar': True}. Best is trial 0 with value: 0.0.

Trial 3 failed with error: Dimension out of range (expected to be in range of [-2, 1], but got 2)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 585, in forward
    self_attention_outputs = self.attention(
                             ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 515, in forward
    self_outputs = self.self(
                   ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 409, in forward
    value_layer = self.transpose_for_scores(self.value(current_states))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 446, in linearBinaryScaling
    x = x_quantizer(x)
        ^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 51, in binary_quantizer
    x = binarised_bipolar_op(x, 0) if bipolar else binarised_zeroScaled_op(x, 0)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
[I 2026-02-03 13:46:20,591] Trial 4 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'integer', 'bert.encoder.layer.0.attention.self.query_int_width': 32, 'bert.encoder.layer.0.attention.self.query_int_frac_width': 8, 'bert.encoder.layer.0.attention.self.query_weight_width': 8, 'bert.encoder.layer.0.attention.self.query_weight_frac_width': 8, 'bert.encoder.layer.0.attention.self.query_bias_width': 8, 'bert.encoder.layer.0.attention.self.query_bias_frac_width': 8, 'bert.encoder.layer.0.attention.self.value_precision_type': 'binary_scaling', 'bert.encoder.layer.0.attention.self.value_bins_x_stochastic': False, 'bert.encoder.layer.0.attention.self.value_bins_x_bipolar': False, 'bert.encoder.layer.0.attention.self.value_bins_w_stochastic': True, 'bert.encoder.layer.0.attention.self.value_bins_w_bipolar': True, 'bert.encoder.layer.0.attention.self.value_bins_b_stochastic': False, 'bert.encoder.layer.0.attention.self.value_bins_b_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'log', 'bert.encoder.layer.0.intermediate.dense_log_width': 4, 'bert.encoder.layer.0.intermediate.dense_log_exp_bias': 15, 'bert.encoder.layer.0.intermediate.dense_log_w_width': 4, 'bert.encoder.layer.0.intermediate.dense_log_w_exp_bias': 15, 'bert.encoder.layer.0.intermediate.dense_log_b_width': 4, 'bert.encoder.layer.0.intermediate.dense_log_b_exp_bias': 7, 'bert.encoder.layer.0.output.dense_precision_type': 'integer', 'bert.encoder.layer.0.output.dense_int_width': 32, 'bert.encoder.layer.0.output.dense_int_frac_width': 2, 'bert.encoder.layer.0.output.dense_weight_width': 16, 'bert.encoder.layer.0.output.dense_weight_frac_width': 8, 'bert.encoder.layer.0.output.dense_bias_width': 32, 'bert.encoder.layer.0.output.dense_bias_frac_width': 2, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'float32', 'bert.encoder.layer.1.intermediate.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.1.intermediate.dense_bins_x_stochastic': True, 'bert.encoder.layer.1.intermediate.dense_bins_x_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bins_w_stochastic': False, 'bert.encoder.layer.1.intermediate.dense_bins_w_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bins_b_stochastic': True, 'bert.encoder.layer.1.intermediate.dense_bins_b_bipolar': False, 'bert.encoder.layer.1.output.dense_precision_type': 'binary', 'bert.encoder.layer.1.output.dense_bin_w_stochastic': False, 'bert.encoder.layer.1.output.dense_bin_w_bipolar': False, 'classifier_precision_type': 'log', 'classifier_log_width': 8, 'classifier_log_exp_bias': 7, 'classifier_log_w_width': 4, 'classifier_log_w_exp_bias': 7, 'classifier_log_b_width': 8, 'classifier_log_b_exp_bias': 7}. Best is trial 0 with value: 0.0.

Trial 4 failed with error: Dimension out of range (expected to be in range of [-3, 2], but got 3)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 627, in forward
    layer_output = apply_chunking_to_forward(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/pytorch_utils.py", line 253, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 639, in feed_forward_chunk
    intermediate_output = self.intermediate(attention_output)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 539, in forward
    hidden_states = self.dense(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 446, in linearBinaryScaling
    x = x_quantizer(x)
        ^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 48, in binary_quantizer
    else binarised_zeroScaled_op(x_sig, x_rand)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
[I 2026-02-03 13:46:21,518] Trial 5 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'log', 'bert.encoder.layer.0.attention.self.query_log_width': 8, 'bert.encoder.layer.0.attention.self.query_log_exp_bias': 15, 'bert.encoder.layer.0.attention.self.query_log_w_width': 4, 'bert.encoder.layer.0.attention.self.query_log_w_exp_bias': 15, 'bert.encoder.layer.0.attention.self.query_log_b_width': 4, 'bert.encoder.layer.0.attention.self.query_log_b_exp_bias': 7, 'bert.encoder.layer.0.attention.self.value_precision_type': 'minifloat_ieee', 'bert.encoder.layer.0.attention.self.value_mfi_width': 8, 'bert.encoder.layer.0.attention.self.value_mfi_exp_width': 4, 'bert.encoder.layer.0.attention.self.value_mfi_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_mfi_w_width': 16, 'bert.encoder.layer.0.attention.self.value_mfi_w_exp_width': 4, 'bert.encoder.layer.0.attention.self.value_mfi_w_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_mfi_b_width': 8, 'bert.encoder.layer.0.attention.self.value_mfi_b_exp_width': 3, 'bert.encoder.layer.0.attention.self.value_mfi_b_exp_bias': 15, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.0.intermediate.dense_mfd_width': 16, 'bert.encoder.layer.0.intermediate.dense_mfd_exp_width': 3, 'bert.encoder.layer.0.intermediate.dense_mfd_exp_bias': 7, 'bert.encoder.layer.0.intermediate.dense_mfd_w_width': 8, 'bert.encoder.layer.0.intermediate.dense_mfd_w_exp_width': 5, 'bert.encoder.layer.0.intermediate.dense_mfd_w_exp_bias': 15, 'bert.encoder.layer.0.intermediate.dense_mfd_b_width': 8, 'bert.encoder.layer.0.intermediate.dense_mfd_b_exp_width': 3, 'bert.encoder.layer.0.intermediate.dense_mfd_b_exp_bias': 7, 'bert.encoder.layer.0.output.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.0.output.dense_bins_x_stochastic': True, 'bert.encoder.layer.0.output.dense_bins_x_bipolar': True, 'bert.encoder.layer.0.output.dense_bins_w_stochastic': False, 'bert.encoder.layer.0.output.dense_bins_w_bipolar': True, 'bert.encoder.layer.0.output.dense_bins_b_stochastic': False, 'bert.encoder.layer.0.output.dense_bins_b_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'integer', 'bert.encoder.layer.1.attention.output.dense_int_width': 32, 'bert.encoder.layer.1.attention.output.dense_int_frac_width': 2, 'bert.encoder.layer.1.attention.output.dense_weight_width': 8, 'bert.encoder.layer.1.attention.output.dense_weight_frac_width': 8, 'bert.encoder.layer.1.attention.output.dense_bias_width': 8, 'bert.encoder.layer.1.attention.output.dense_bias_frac_width': 2, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.1.intermediate.dense_bins_x_stochastic': True, 'bert.encoder.layer.1.intermediate.dense_bins_x_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bins_w_stochastic': False, 'bert.encoder.layer.1.intermediate.dense_bins_w_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bins_b_stochastic': False, 'bert.encoder.layer.1.intermediate.dense_bins_b_bipolar': True, 'bert.encoder.layer.1.output.dense_precision_type': 'integer', 'bert.encoder.layer.1.output.dense_int_width': 32, 'bert.encoder.layer.1.output.dense_int_frac_width': 4, 'bert.encoder.layer.1.output.dense_weight_width': 8, 'bert.encoder.layer.1.output.dense_weight_frac_width': 2, 'bert.encoder.layer.1.output.dense_bias_width': 32, 'bert.encoder.layer.1.output.dense_bias_frac_width': 4, 'classifier_precision_type': 'binary', 'classifier_bin_w_stochastic': False, 'classifier_bin_w_bipolar': False}. Best is trial 0 with value: 0.0.

Trial 5 failed with error: Dimension out of range (expected to be in range of [-3, 2], but got 3)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 627, in forward
    layer_output = apply_chunking_to_forward(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/pytorch_utils.py", line 253, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 640, in feed_forward_chunk
    layer_output = self.output(intermediate_output, attention_output)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 552, in forward
    hidden_states = self.dense(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 448, in linearBinaryScaling
    bias = b_quantizer(bias) if bias is not None else None
           ^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 51, in binary_quantizer
    x = binarised_bipolar_op(x, 0) if bipolar else binarised_zeroScaled_op(x, 0)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
[I 2026-02-03 13:46:22,426] Trial 6 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'integer', 'bert.encoder.layer.0.attention.self.query_int_width': 32, 'bert.encoder.layer.0.attention.self.query_int_frac_width': 8, 'bert.encoder.layer.0.attention.self.query_weight_width': 32, 'bert.encoder.layer.0.attention.self.query_weight_frac_width': 2, 'bert.encoder.layer.0.attention.self.query_bias_width': 8, 'bert.encoder.layer.0.attention.self.query_bias_frac_width': 4, 'bert.encoder.layer.0.attention.self.value_precision_type': 'integer', 'bert.encoder.layer.0.attention.self.value_int_width': 8, 'bert.encoder.layer.0.attention.self.value_int_frac_width': 4, 'bert.encoder.layer.0.attention.self.value_weight_width': 8, 'bert.encoder.layer.0.attention.self.value_weight_frac_width': 8, 'bert.encoder.layer.0.attention.self.value_bias_width': 32, 'bert.encoder.layer.0.attention.self.value_bias_frac_width': 2, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'binary', 'bert.encoder.layer.0.intermediate.dense_bin_w_stochastic': True, 'bert.encoder.layer.0.intermediate.dense_bin_w_bipolar': True, 'bert.encoder.layer.0.output.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.0.output.dense_bins_x_stochastic': True, 'bert.encoder.layer.0.output.dense_bins_x_bipolar': True, 'bert.encoder.layer.0.output.dense_bins_w_stochastic': True, 'bert.encoder.layer.0.output.dense_bins_w_bipolar': True, 'bert.encoder.layer.0.output.dense_bins_b_stochastic': False, 'bert.encoder.layer.0.output.dense_bins_b_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'log', 'bert.encoder.layer.1.attention.output.dense_log_width': 8, 'bert.encoder.layer.1.attention.output.dense_log_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_log_w_width': 4, 'bert.encoder.layer.1.attention.output.dense_log_w_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_log_b_width': 8, 'bert.encoder.layer.1.attention.output.dense_log_b_exp_bias': 7, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'float32', 'bert.encoder.layer.1.output.dense_precision_type': 'integer', 'bert.encoder.layer.1.output.dense_int_width': 16, 'bert.encoder.layer.1.output.dense_int_frac_width': 2, 'bert.encoder.layer.1.output.dense_weight_width': 16, 'bert.encoder.layer.1.output.dense_weight_frac_width': 8, 'bert.encoder.layer.1.output.dense_bias_width': 16, 'bert.encoder.layer.1.output.dense_bias_frac_width': 8, 'classifier_precision_type': 'minifloat_denorm', 'classifier_mfd_width': 16, 'classifier_mfd_exp_width': 3, 'classifier_mfd_exp_bias': 15, 'classifier_mfd_w_width': 16, 'classifier_mfd_w_exp_width': 3, 'classifier_mfd_w_exp_bias': 7, 'classifier_mfd_b_width': 16, 'classifier_mfd_b_exp_width': 4, 'classifier_mfd_b_exp_bias': 15}. Best is trial 0 with value: 0.0.

Trial 6 failed with error: Dimension out of range (expected to be in range of [-1, 0], but got 1)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 585, in forward
    self_attention_outputs = self.attention(
                             ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 515, in forward
    self_outputs = self.self(
                   ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 395, in forward
    query_layer = self.transpose_for_scores(self.query(hidden_states))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 446, in linearBinaryScaling
    x = x_quantizer(x)
        ^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 51, in binary_quantizer
    x = binarised_bipolar_op(x, 0) if bipolar else binarised_zeroScaled_op(x, 0)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
[I 2026-02-03 13:46:23,335] Trial 7 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'binary_scaling', 'bert.encoder.layer.0.attention.self.query_bins_x_stochastic': False, 'bert.encoder.layer.0.attention.self.query_bins_x_bipolar': False, 'bert.encoder.layer.0.attention.self.query_bins_w_stochastic': True, 'bert.encoder.layer.0.attention.self.query_bins_w_bipolar': True, 'bert.encoder.layer.0.attention.self.query_bins_b_stochastic': True, 'bert.encoder.layer.0.attention.self.query_bins_b_bipolar': True, 'bert.encoder.layer.0.attention.self.value_precision_type': 'binary', 'bert.encoder.layer.0.attention.self.value_bin_w_stochastic': False, 'bert.encoder.layer.0.attention.self.value_bin_w_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'integer', 'bert.encoder.layer.0.intermediate.dense_int_width': 16, 'bert.encoder.layer.0.intermediate.dense_int_frac_width': 4, 'bert.encoder.layer.0.intermediate.dense_weight_width': 8, 'bert.encoder.layer.0.intermediate.dense_weight_frac_width': 8, 'bert.encoder.layer.0.intermediate.dense_bias_width': 32, 'bert.encoder.layer.0.intermediate.dense_bias_frac_width': 8, 'bert.encoder.layer.0.output.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.0.output.dense_bins_x_stochastic': True, 'bert.encoder.layer.0.output.dense_bins_x_bipolar': True, 'bert.encoder.layer.0.output.dense_bins_w_stochastic': True, 'bert.encoder.layer.0.output.dense_bins_w_bipolar': False, 'bert.encoder.layer.0.output.dense_bins_b_stochastic': False, 'bert.encoder.layer.0.output.dense_bins_b_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.1.attention.output.dense_mfd_width': 16, 'bert.encoder.layer.1.attention.output.dense_mfd_exp_width': 4, 'bert.encoder.layer.1.attention.output.dense_mfd_exp_bias': 15, 'bert.encoder.layer.1.attention.output.dense_mfd_w_width': 16, 'bert.encoder.layer.1.attention.output.dense_mfd_w_exp_width': 3, 'bert.encoder.layer.1.attention.output.dense_mfd_w_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_mfd_b_width': 8, 'bert.encoder.layer.1.attention.output.dense_mfd_b_exp_width': 5, 'bert.encoder.layer.1.attention.output.dense_mfd_b_exp_bias': 15, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'log', 'bert.encoder.layer.1.intermediate.dense_log_width': 8, 'bert.encoder.layer.1.intermediate.dense_log_exp_bias': 7, 'bert.encoder.layer.1.intermediate.dense_log_w_width': 4, 'bert.encoder.layer.1.intermediate.dense_log_w_exp_bias': 15, 'bert.encoder.layer.1.intermediate.dense_log_b_width': 8, 'bert.encoder.layer.1.intermediate.dense_log_b_exp_bias': 7, 'bert.encoder.layer.1.output.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.1.output.dense_bins_x_stochastic': False, 'bert.encoder.layer.1.output.dense_bins_x_bipolar': True, 'bert.encoder.layer.1.output.dense_bins_w_stochastic': True, 'bert.encoder.layer.1.output.dense_bins_w_bipolar': False, 'bert.encoder.layer.1.output.dense_bins_b_stochastic': True, 'bert.encoder.layer.1.output.dense_bins_b_bipolar': False, 'classifier_precision_type': 'binary_scaling', 'classifier_bins_x_stochastic': False, 'classifier_bins_x_bipolar': True, 'classifier_bins_w_stochastic': False, 'classifier_bins_w_bipolar': False, 'classifier_bins_b_stochastic': True, 'classifier_bins_b_bipolar': False}. Best is trial 0 with value: 0.0.

Trial 7 failed with error: Dimension out of range (expected to be in range of [-3, 2], but got 3)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 627, in forward
    layer_output = apply_chunking_to_forward(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/pytorch_utils.py", line 253, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 639, in feed_forward_chunk
    intermediate_output = self.intermediate(attention_output)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 539, in forward
    hidden_states = self.dense(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 446, in linearBinaryScaling
    x = x_quantizer(x)
        ^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 48, in binary_quantizer
    else binarised_zeroScaled_op(x_sig, x_rand)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
[I 2026-02-03 13:46:24,239] Trial 8 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'float32', 'bert.encoder.layer.0.attention.self.value_precision_type': 'float32', 'bert.encoder.layer.0.intermediate.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.0.intermediate.dense_bins_x_stochastic': True, 'bert.encoder.layer.0.intermediate.dense_bins_x_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_bins_w_stochastic': False, 'bert.encoder.layer.0.intermediate.dense_bins_w_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bins_b_stochastic': True, 'bert.encoder.layer.0.intermediate.dense_bins_b_bipolar': False, 'bert.encoder.layer.0.output.dense_precision_type': 'minifloat_ieee', 'bert.encoder.layer.0.output.dense_mfi_width': 8, 'bert.encoder.layer.0.output.dense_mfi_exp_width': 5, 'bert.encoder.layer.0.output.dense_mfi_exp_bias': 15, 'bert.encoder.layer.0.output.dense_mfi_w_width': 16, 'bert.encoder.layer.0.output.dense_mfi_w_exp_width': 3, 'bert.encoder.layer.0.output.dense_mfi_w_exp_bias': 7, 'bert.encoder.layer.0.output.dense_mfi_b_width': 8, 'bert.encoder.layer.0.output.dense_mfi_b_exp_width': 4, 'bert.encoder.layer.0.output.dense_mfi_b_exp_bias': 15, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'float32', 'bert.encoder.layer.1.intermediate.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.1.intermediate.dense_bins_x_stochastic': True, 'bert.encoder.layer.1.intermediate.dense_bins_x_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bins_w_stochastic': False, 'bert.encoder.layer.1.intermediate.dense_bins_w_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bins_b_stochastic': True, 'bert.encoder.layer.1.intermediate.dense_bins_b_bipolar': False, 'bert.encoder.layer.1.output.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.1.output.dense_mfd_width': 8, 'bert.encoder.layer.1.output.dense_mfd_exp_width': 3, 'bert.encoder.layer.1.output.dense_mfd_exp_bias': 7, 'bert.encoder.layer.1.output.dense_mfd_w_width': 8, 'bert.encoder.layer.1.output.dense_mfd_w_exp_width': 5, 'bert.encoder.layer.1.output.dense_mfd_w_exp_bias': 7, 'bert.encoder.layer.1.output.dense_mfd_b_width': 16, 'bert.encoder.layer.1.output.dense_mfd_b_exp_width': 4, 'bert.encoder.layer.1.output.dense_mfd_b_exp_bias': 7, 'classifier_precision_type': 'float32'}. Best is trial 0 with value: 0.0.

Trial 8 failed with error: Dimension out of range (expected to be in range of [-3, 2], but got 3)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-03 13:48:18,474] Trial 9 finished with value: 0.86012 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'log', 'bert.encoder.layer.0.attention.self.query_log_width': 8, 'bert.encoder.layer.0.attention.self.query_log_exp_bias': 7, 'bert.encoder.layer.0.attention.self.query_log_w_width': 4, 'bert.encoder.layer.0.attention.self.query_log_w_exp_bias': 15, 'bert.encoder.layer.0.attention.self.query_log_b_width': 8, 'bert.encoder.layer.0.attention.self.query_log_b_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_precision_type': 'float32', 'bert.encoder.layer.0.intermediate.dense_precision_type': 'integer', 'bert.encoder.layer.0.intermediate.dense_int_width': 8, 'bert.encoder.layer.0.intermediate.dense_int_frac_width': 2, 'bert.encoder.layer.0.intermediate.dense_weight_width': 32, 'bert.encoder.layer.0.intermediate.dense_weight_frac_width': 2, 'bert.encoder.layer.0.intermediate.dense_bias_width': 32, 'bert.encoder.layer.0.intermediate.dense_bias_frac_width': 2, 'bert.encoder.layer.0.output.dense_precision_type': 'integer', 'bert.encoder.layer.0.output.dense_int_width': 8, 'bert.encoder.layer.0.output.dense_int_frac_width': 2, 'bert.encoder.layer.0.output.dense_weight_width': 8, 'bert.encoder.layer.0.output.dense_weight_frac_width': 4, 'bert.encoder.layer.0.output.dense_bias_width': 8, 'bert.encoder.layer.0.output.dense_bias_frac_width': 4, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'integer', 'bert.encoder.layer.1.attention.output.dense_int_width': 16, 'bert.encoder.layer.1.attention.output.dense_int_frac_width': 2, 'bert.encoder.layer.1.attention.output.dense_weight_width': 16, 'bert.encoder.layer.1.attention.output.dense_weight_frac_width': 8, 'bert.encoder.layer.1.attention.output.dense_bias_width': 8, 'bert.encoder.layer.1.attention.output.dense_bias_frac_width': 8, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.1.intermediate.dense_bins_x_stochastic': False, 'bert.encoder.layer.1.intermediate.dense_bins_x_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bins_w_stochastic': False, 'bert.encoder.layer.1.intermediate.dense_bins_w_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bins_b_stochastic': True, 'bert.encoder.layer.1.intermediate.dense_bins_b_bipolar': True, 'bert.encoder.layer.1.output.dense_precision_type': 'binary', 'bert.encoder.layer.1.output.dense_bin_w_stochastic': True, 'bert.encoder.layer.1.output.dense_bin_w_bipolar': True, 'classifier_precision_type': 'minifloat_denorm', 'classifier_mfd_width': 8, 'classifier_mfd_exp_width': 4, 'classifier_mfd_exp_bias': 15, 'classifier_mfd_w_width': 16, 'classifier_mfd_w_exp_width': 5, 'classifier_mfd_w_exp_bias': 7, 'classifier_mfd_b_width': 16, 'classifier_mfd_b_exp_width': 3, 'classifier_mfd_b_exp_bias': 15}. Best is trial 9 with value: 0.86012.
/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 585, in forward
    self_attention_outputs = self.attention(
                             ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 515, in forward
    self_outputs = self.self(
                   ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 395, in forward
    query_layer = self.transpose_for_scores(self.query(hidden_states))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 288, in forward
    return linearBinary(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 408, in linearBinary
    weight = w_quantizer(weight)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 51, in binary_quantizer
    x = binarised_bipolar_op(x, 0) if bipolar else binarised_zeroScaled_op(x, 0)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
[I 2026-02-03 13:48:19,437] Trial 10 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'binary', 'bert.encoder.layer.0.attention.self.query_bin_w_stochastic': False, 'bert.encoder.layer.0.attention.self.query_bin_w_bipolar': False, 'bert.encoder.layer.0.attention.self.value_precision_type': 'log', 'bert.encoder.layer.0.attention.self.value_log_width': 4, 'bert.encoder.layer.0.attention.self.value_log_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_log_w_width': 8, 'bert.encoder.layer.0.attention.self.value_log_w_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_log_b_width': 4, 'bert.encoder.layer.0.attention.self.value_log_b_exp_bias': 15, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'binary', 'bert.encoder.layer.0.intermediate.dense_bin_w_stochastic': True, 'bert.encoder.layer.0.intermediate.dense_bin_w_bipolar': True, 'bert.encoder.layer.0.output.dense_precision_type': 'minifloat_ieee', 'bert.encoder.layer.0.output.dense_mfi_width': 8, 'bert.encoder.layer.0.output.dense_mfi_exp_width': 5, 'bert.encoder.layer.0.output.dense_mfi_exp_bias': 7, 'bert.encoder.layer.0.output.dense_mfi_w_width': 8, 'bert.encoder.layer.0.output.dense_mfi_w_exp_width': 3, 'bert.encoder.layer.0.output.dense_mfi_w_exp_bias': 7, 'bert.encoder.layer.0.output.dense_mfi_b_width': 16, 'bert.encoder.layer.0.output.dense_mfi_b_exp_width': 5, 'bert.encoder.layer.0.output.dense_mfi_b_exp_bias': 15, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.1.attention.output.dense_mfd_width': 16, 'bert.encoder.layer.1.attention.output.dense_mfd_exp_width': 3, 'bert.encoder.layer.1.attention.output.dense_mfd_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_mfd_w_width': 8, 'bert.encoder.layer.1.attention.output.dense_mfd_w_exp_width': 4, 'bert.encoder.layer.1.attention.output.dense_mfd_w_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_mfd_b_width': 16, 'bert.encoder.layer.1.attention.output.dense_mfd_b_exp_width': 3, 'bert.encoder.layer.1.attention.output.dense_mfd_b_exp_bias': 15, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'float32', 'bert.encoder.layer.1.output.dense_precision_type': 'integer', 'bert.encoder.layer.1.output.dense_int_width': 8, 'bert.encoder.layer.1.output.dense_int_frac_width': 2, 'bert.encoder.layer.1.output.dense_weight_width': 16, 'bert.encoder.layer.1.output.dense_weight_frac_width': 4, 'bert.encoder.layer.1.output.dense_bias_width': 32, 'bert.encoder.layer.1.output.dense_bias_frac_width': 2, 'classifier_precision_type': 'log', 'classifier_log_width': 8, 'classifier_log_exp_bias': 15, 'classifier_log_w_width': 4, 'classifier_log_w_exp_bias': 15, 'classifier_log_b_width': 8, 'classifier_log_b_exp_bias': 15}. Best is trial 9 with value: 0.86012.

Trial 10 failed with error: Dimension out of range (expected to be in range of [-2, 1], but got 2)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 585, in forward
    self_attention_outputs = self.attention(
                             ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 515, in forward
    self_outputs = self.self(
                   ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 409, in forward
    value_layer = self.transpose_for_scores(self.value(current_states))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 446, in linearBinaryScaling
    x = x_quantizer(x)
        ^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 51, in binary_quantizer
    x = binarised_bipolar_op(x, 0) if bipolar else binarised_zeroScaled_op(x, 0)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
[I 2026-02-03 13:48:20,335] Trial 11 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'log', 'bert.encoder.layer.0.attention.self.query_log_width': 4, 'bert.encoder.layer.0.attention.self.query_log_exp_bias': 15, 'bert.encoder.layer.0.attention.self.query_log_w_width': 8, 'bert.encoder.layer.0.attention.self.query_log_w_exp_bias': 7, 'bert.encoder.layer.0.attention.self.query_log_b_width': 4, 'bert.encoder.layer.0.attention.self.query_log_b_exp_bias': 7, 'bert.encoder.layer.0.attention.self.value_precision_type': 'binary_scaling', 'bert.encoder.layer.0.attention.self.value_bins_x_stochastic': False, 'bert.encoder.layer.0.attention.self.value_bins_x_bipolar': False, 'bert.encoder.layer.0.attention.self.value_bins_w_stochastic': False, 'bert.encoder.layer.0.attention.self.value_bins_w_bipolar': True, 'bert.encoder.layer.0.attention.self.value_bins_b_stochastic': True, 'bert.encoder.layer.0.attention.self.value_bins_b_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.0.intermediate.dense_mfd_width': 16, 'bert.encoder.layer.0.intermediate.dense_mfd_exp_width': 4, 'bert.encoder.layer.0.intermediate.dense_mfd_exp_bias': 15, 'bert.encoder.layer.0.intermediate.dense_mfd_w_width': 16, 'bert.encoder.layer.0.intermediate.dense_mfd_w_exp_width': 3, 'bert.encoder.layer.0.intermediate.dense_mfd_w_exp_bias': 7, 'bert.encoder.layer.0.intermediate.dense_mfd_b_width': 16, 'bert.encoder.layer.0.intermediate.dense_mfd_b_exp_width': 5, 'bert.encoder.layer.0.intermediate.dense_mfd_b_exp_bias': 15, 'bert.encoder.layer.0.output.dense_precision_type': 'float32', 'bert.encoder.layer.1.attention.output.dense_precision_type': 'minifloat_ieee', 'bert.encoder.layer.1.attention.output.dense_mfi_width': 16, 'bert.encoder.layer.1.attention.output.dense_mfi_exp_width': 3, 'bert.encoder.layer.1.attention.output.dense_mfi_exp_bias': 15, 'bert.encoder.layer.1.attention.output.dense_mfi_w_width': 8, 'bert.encoder.layer.1.attention.output.dense_mfi_w_exp_width': 4, 'bert.encoder.layer.1.attention.output.dense_mfi_w_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_mfi_b_width': 16, 'bert.encoder.layer.1.attention.output.dense_mfi_b_exp_width': 4, 'bert.encoder.layer.1.attention.output.dense_mfi_b_exp_bias': 15, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'binary', 'bert.encoder.layer.1.intermediate.dense_bin_w_stochastic': False, 'bert.encoder.layer.1.intermediate.dense_bin_w_bipolar': True, 'bert.encoder.layer.1.output.dense_precision_type': 'binary', 'bert.encoder.layer.1.output.dense_bin_w_stochastic': True, 'bert.encoder.layer.1.output.dense_bin_w_bipolar': False, 'classifier_precision_type': 'log', 'classifier_log_width': 8, 'classifier_log_exp_bias': 7, 'classifier_log_w_width': 8, 'classifier_log_w_exp_bias': 7, 'classifier_log_b_width': 4, 'classifier_log_b_exp_bias': 7}. Best is trial 9 with value: 0.86012.

Trial 11 failed with error: Dimension out of range (expected to be in range of [-3, 2], but got 3)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 585, in forward
    self_attention_outputs = self.attention(
                             ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 515, in forward
    self_outputs = self.self(
                   ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 409, in forward
    value_layer = self.transpose_for_scores(self.value(current_states))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 288, in forward
    return linearBinary(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 408, in linearBinary
    weight = w_quantizer(weight)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 51, in binary_quantizer
    x = binarised_bipolar_op(x, 0) if bipolar else binarised_zeroScaled_op(x, 0)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
[I 2026-02-03 13:48:21,241] Trial 12 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'integer', 'bert.encoder.layer.0.attention.self.query_int_width': 8, 'bert.encoder.layer.0.attention.self.query_int_frac_width': 2, 'bert.encoder.layer.0.attention.self.query_weight_width': 16, 'bert.encoder.layer.0.attention.self.query_weight_frac_width': 4, 'bert.encoder.layer.0.attention.self.query_bias_width': 8, 'bert.encoder.layer.0.attention.self.query_bias_frac_width': 4, 'bert.encoder.layer.0.attention.self.value_precision_type': 'binary', 'bert.encoder.layer.0.attention.self.value_bin_w_stochastic': False, 'bert.encoder.layer.0.attention.self.value_bin_w_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'minifloat_ieee', 'bert.encoder.layer.0.intermediate.dense_mfi_width': 16, 'bert.encoder.layer.0.intermediate.dense_mfi_exp_width': 3, 'bert.encoder.layer.0.intermediate.dense_mfi_exp_bias': 7, 'bert.encoder.layer.0.intermediate.dense_mfi_w_width': 16, 'bert.encoder.layer.0.intermediate.dense_mfi_w_exp_width': 4, 'bert.encoder.layer.0.intermediate.dense_mfi_w_exp_bias': 7, 'bert.encoder.layer.0.intermediate.dense_mfi_b_width': 16, 'bert.encoder.layer.0.intermediate.dense_mfi_b_exp_width': 4, 'bert.encoder.layer.0.intermediate.dense_mfi_b_exp_bias': 7, 'bert.encoder.layer.0.output.dense_precision_type': 'log', 'bert.encoder.layer.0.output.dense_log_width': 4, 'bert.encoder.layer.0.output.dense_log_exp_bias': 7, 'bert.encoder.layer.0.output.dense_log_w_width': 4, 'bert.encoder.layer.0.output.dense_log_w_exp_bias': 7, 'bert.encoder.layer.0.output.dense_log_b_width': 4, 'bert.encoder.layer.0.output.dense_log_b_exp_bias': 15, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.1.attention.output.dense_bins_x_stochastic': False, 'bert.encoder.layer.1.attention.output.dense_bins_x_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_bins_w_stochastic': False, 'bert.encoder.layer.1.attention.output.dense_bins_w_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bins_b_stochastic': True, 'bert.encoder.layer.1.attention.output.dense_bins_b_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'binary', 'bert.encoder.layer.1.intermediate.dense_bin_w_stochastic': True, 'bert.encoder.layer.1.intermediate.dense_bin_w_bipolar': True, 'bert.encoder.layer.1.output.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.1.output.dense_bins_x_stochastic': False, 'bert.encoder.layer.1.output.dense_bins_x_bipolar': True, 'bert.encoder.layer.1.output.dense_bins_w_stochastic': True, 'bert.encoder.layer.1.output.dense_bins_w_bipolar': True, 'bert.encoder.layer.1.output.dense_bins_b_stochastic': True, 'bert.encoder.layer.1.output.dense_bins_b_bipolar': True, 'classifier_precision_type': 'minifloat_ieee', 'classifier_mfi_width': 16, 'classifier_mfi_exp_width': 3, 'classifier_mfi_exp_bias': 7, 'classifier_mfi_w_width': 16, 'classifier_mfi_w_exp_width': 3, 'classifier_mfi_w_exp_bias': 15, 'classifier_mfi_b_width': 16, 'classifier_mfi_b_exp_width': 4, 'classifier_mfi_b_exp_bias': 7}. Best is trial 9 with value: 0.86012.

Trial 12 failed with error: Dimension out of range (expected to be in range of [-2, 1], but got 2)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 585, in forward
    self_attention_outputs = self.attention(
                             ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 515, in forward
    self_outputs = self.self(
                   ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 409, in forward
    value_layer = self.transpose_for_scores(self.value(current_states))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 288, in forward
    return linearBinary(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 408, in linearBinary
    weight = w_quantizer(weight)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 48, in binary_quantizer
    else binarised_zeroScaled_op(x_sig, x_rand)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
[I 2026-02-03 13:48:22,164] Trial 13 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'minifloat_ieee', 'bert.encoder.layer.0.attention.self.query_mfi_width': 8, 'bert.encoder.layer.0.attention.self.query_mfi_exp_width': 5, 'bert.encoder.layer.0.attention.self.query_mfi_exp_bias': 15, 'bert.encoder.layer.0.attention.self.query_mfi_w_width': 8, 'bert.encoder.layer.0.attention.self.query_mfi_w_exp_width': 5, 'bert.encoder.layer.0.attention.self.query_mfi_w_exp_bias': 7, 'bert.encoder.layer.0.attention.self.query_mfi_b_width': 16, 'bert.encoder.layer.0.attention.self.query_mfi_b_exp_width': 4, 'bert.encoder.layer.0.attention.self.query_mfi_b_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_precision_type': 'binary', 'bert.encoder.layer.0.attention.self.value_bin_w_stochastic': True, 'bert.encoder.layer.0.attention.self.value_bin_w_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'minifloat_ieee', 'bert.encoder.layer.0.intermediate.dense_mfi_width': 8, 'bert.encoder.layer.0.intermediate.dense_mfi_exp_width': 4, 'bert.encoder.layer.0.intermediate.dense_mfi_exp_bias': 7, 'bert.encoder.layer.0.intermediate.dense_mfi_w_width': 8, 'bert.encoder.layer.0.intermediate.dense_mfi_w_exp_width': 3, 'bert.encoder.layer.0.intermediate.dense_mfi_w_exp_bias': 7, 'bert.encoder.layer.0.intermediate.dense_mfi_b_width': 16, 'bert.encoder.layer.0.intermediate.dense_mfi_b_exp_width': 4, 'bert.encoder.layer.0.intermediate.dense_mfi_b_exp_bias': 15, 'bert.encoder.layer.0.output.dense_precision_type': 'float32', 'bert.encoder.layer.1.attention.output.dense_precision_type': 'binary', 'bert.encoder.layer.1.attention.output.dense_bin_w_stochastic': False, 'bert.encoder.layer.1.attention.output.dense_bin_w_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'log', 'bert.encoder.layer.1.intermediate.dense_log_width': 8, 'bert.encoder.layer.1.intermediate.dense_log_exp_bias': 7, 'bert.encoder.layer.1.intermediate.dense_log_w_width': 4, 'bert.encoder.layer.1.intermediate.dense_log_w_exp_bias': 7, 'bert.encoder.layer.1.intermediate.dense_log_b_width': 8, 'bert.encoder.layer.1.intermediate.dense_log_b_exp_bias': 7, 'bert.encoder.layer.1.output.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.1.output.dense_mfd_width': 8, 'bert.encoder.layer.1.output.dense_mfd_exp_width': 3, 'bert.encoder.layer.1.output.dense_mfd_exp_bias': 15, 'bert.encoder.layer.1.output.dense_mfd_w_width': 8, 'bert.encoder.layer.1.output.dense_mfd_w_exp_width': 5, 'bert.encoder.layer.1.output.dense_mfd_w_exp_bias': 15, 'bert.encoder.layer.1.output.dense_mfd_b_width': 8, 'bert.encoder.layer.1.output.dense_mfd_b_exp_width': 4, 'bert.encoder.layer.1.output.dense_mfd_b_exp_bias': 7, 'classifier_precision_type': 'float32'}. Best is trial 9 with value: 0.86012.

Trial 13 failed with error: Dimension out of range (expected to be in range of [-2, 1], but got 2)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1690, in forward
    logits = self.classifier(pooled_output)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 447, in linearBinaryScaling
    w = w_quantizer(weight)
        ^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 51, in binary_quantizer
    x = binarised_bipolar_op(x, 0) if bipolar else binarised_zeroScaled_op(x, 0)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
[I 2026-02-03 13:48:23,384] Trial 14 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'minifloat_ieee', 'bert.encoder.layer.0.attention.self.query_mfi_width': 16, 'bert.encoder.layer.0.attention.self.query_mfi_exp_width': 5, 'bert.encoder.layer.0.attention.self.query_mfi_exp_bias': 15, 'bert.encoder.layer.0.attention.self.query_mfi_w_width': 8, 'bert.encoder.layer.0.attention.self.query_mfi_w_exp_width': 3, 'bert.encoder.layer.0.attention.self.query_mfi_w_exp_bias': 7, 'bert.encoder.layer.0.attention.self.query_mfi_b_width': 8, 'bert.encoder.layer.0.attention.self.query_mfi_b_exp_width': 4, 'bert.encoder.layer.0.attention.self.query_mfi_b_exp_bias': 7, 'bert.encoder.layer.0.attention.self.value_precision_type': 'log', 'bert.encoder.layer.0.attention.self.value_log_width': 8, 'bert.encoder.layer.0.attention.self.value_log_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_log_w_width': 8, 'bert.encoder.layer.0.attention.self.value_log_w_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_log_b_width': 8, 'bert.encoder.layer.0.attention.self.value_log_b_exp_bias': 15, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'binary', 'bert.encoder.layer.0.intermediate.dense_bin_w_stochastic': True, 'bert.encoder.layer.0.intermediate.dense_bin_w_bipolar': True, 'bert.encoder.layer.0.output.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.0.output.dense_mfd_width': 16, 'bert.encoder.layer.0.output.dense_mfd_exp_width': 5, 'bert.encoder.layer.0.output.dense_mfd_exp_bias': 7, 'bert.encoder.layer.0.output.dense_mfd_w_width': 16, 'bert.encoder.layer.0.output.dense_mfd_w_exp_width': 3, 'bert.encoder.layer.0.output.dense_mfd_w_exp_bias': 15, 'bert.encoder.layer.0.output.dense_mfd_b_width': 16, 'bert.encoder.layer.0.output.dense_mfd_b_exp_width': 4, 'bert.encoder.layer.0.output.dense_mfd_b_exp_bias': 15, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'log', 'bert.encoder.layer.1.attention.output.dense_log_width': 4, 'bert.encoder.layer.1.attention.output.dense_log_exp_bias': 15, 'bert.encoder.layer.1.attention.output.dense_log_w_width': 8, 'bert.encoder.layer.1.attention.output.dense_log_w_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_log_b_width': 4, 'bert.encoder.layer.1.attention.output.dense_log_b_exp_bias': 15, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.1.intermediate.dense_mfd_width': 8, 'bert.encoder.layer.1.intermediate.dense_mfd_exp_width': 4, 'bert.encoder.layer.1.intermediate.dense_mfd_exp_bias': 15, 'bert.encoder.layer.1.intermediate.dense_mfd_w_width': 8, 'bert.encoder.layer.1.intermediate.dense_mfd_w_exp_width': 4, 'bert.encoder.layer.1.intermediate.dense_mfd_w_exp_bias': 7, 'bert.encoder.layer.1.intermediate.dense_mfd_b_width': 8, 'bert.encoder.layer.1.intermediate.dense_mfd_b_exp_width': 4, 'bert.encoder.layer.1.intermediate.dense_mfd_b_exp_bias': 7, 'bert.encoder.layer.1.output.dense_precision_type': 'minifloat_ieee', 'bert.encoder.layer.1.output.dense_mfi_width': 16, 'bert.encoder.layer.1.output.dense_mfi_exp_width': 5, 'bert.encoder.layer.1.output.dense_mfi_exp_bias': 7, 'bert.encoder.layer.1.output.dense_mfi_w_width': 8, 'bert.encoder.layer.1.output.dense_mfi_w_exp_width': 4, 'bert.encoder.layer.1.output.dense_mfi_w_exp_bias': 15, 'bert.encoder.layer.1.output.dense_mfi_b_width': 16, 'bert.encoder.layer.1.output.dense_mfi_b_exp_width': 5, 'bert.encoder.layer.1.output.dense_mfi_b_exp_bias': 7, 'classifier_precision_type': 'binary_scaling', 'classifier_bins_x_stochastic': False, 'classifier_bins_x_bipolar': True, 'classifier_bins_w_stochastic': False, 'classifier_bins_w_bipolar': False, 'classifier_bins_b_stochastic': True, 'classifier_bins_b_bipolar': True}. Best is trial 9 with value: 0.86012.

Trial 14 failed with error: Dimension out of range (expected to be in range of [-2, 1], but got 2)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 627, in forward
    layer_output = apply_chunking_to_forward(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/pytorch_utils.py", line 253, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 639, in feed_forward_chunk
    intermediate_output = self.intermediate(attention_output)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 539, in forward
    hidden_states = self.dense(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 446, in linearBinaryScaling
    x = x_quantizer(x)
        ^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 48, in binary_quantizer
    else binarised_zeroScaled_op(x_sig, x_rand)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
[I 2026-02-03 13:48:24,312] Trial 15 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'minifloat_ieee', 'bert.encoder.layer.0.attention.self.query_mfi_width': 8, 'bert.encoder.layer.0.attention.self.query_mfi_exp_width': 4, 'bert.encoder.layer.0.attention.self.query_mfi_exp_bias': 7, 'bert.encoder.layer.0.attention.self.query_mfi_w_width': 16, 'bert.encoder.layer.0.attention.self.query_mfi_w_exp_width': 3, 'bert.encoder.layer.0.attention.self.query_mfi_w_exp_bias': 7, 'bert.encoder.layer.0.attention.self.query_mfi_b_width': 8, 'bert.encoder.layer.0.attention.self.query_mfi_b_exp_width': 5, 'bert.encoder.layer.0.attention.self.query_mfi_b_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_precision_type': 'float32', 'bert.encoder.layer.0.intermediate.dense_precision_type': 'binary', 'bert.encoder.layer.0.intermediate.dense_bin_w_stochastic': True, 'bert.encoder.layer.0.intermediate.dense_bin_w_bipolar': True, 'bert.encoder.layer.0.output.dense_precision_type': 'log', 'bert.encoder.layer.0.output.dense_log_width': 4, 'bert.encoder.layer.0.output.dense_log_exp_bias': 7, 'bert.encoder.layer.0.output.dense_log_w_width': 4, 'bert.encoder.layer.0.output.dense_log_w_exp_bias': 15, 'bert.encoder.layer.0.output.dense_log_b_width': 4, 'bert.encoder.layer.0.output.dense_log_b_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'minifloat_ieee', 'bert.encoder.layer.1.attention.output.dense_mfi_width': 16, 'bert.encoder.layer.1.attention.output.dense_mfi_exp_width': 3, 'bert.encoder.layer.1.attention.output.dense_mfi_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_mfi_w_width': 8, 'bert.encoder.layer.1.attention.output.dense_mfi_w_exp_width': 3, 'bert.encoder.layer.1.attention.output.dense_mfi_w_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_mfi_b_width': 16, 'bert.encoder.layer.1.attention.output.dense_mfi_b_exp_width': 3, 'bert.encoder.layer.1.attention.output.dense_mfi_b_exp_bias': 7, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.1.intermediate.dense_bins_x_stochastic': True, 'bert.encoder.layer.1.intermediate.dense_bins_x_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bins_w_stochastic': False, 'bert.encoder.layer.1.intermediate.dense_bins_w_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bins_b_stochastic': False, 'bert.encoder.layer.1.intermediate.dense_bins_b_bipolar': False, 'bert.encoder.layer.1.output.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.1.output.dense_mfd_width': 16, 'bert.encoder.layer.1.output.dense_mfd_exp_width': 5, 'bert.encoder.layer.1.output.dense_mfd_exp_bias': 15, 'bert.encoder.layer.1.output.dense_mfd_w_width': 16, 'bert.encoder.layer.1.output.dense_mfd_w_exp_width': 4, 'bert.encoder.layer.1.output.dense_mfd_w_exp_bias': 15, 'bert.encoder.layer.1.output.dense_mfd_b_width': 16, 'bert.encoder.layer.1.output.dense_mfd_b_exp_width': 3, 'bert.encoder.layer.1.output.dense_mfd_b_exp_bias': 15, 'classifier_precision_type': 'binary_scaling', 'classifier_bins_x_stochastic': True, 'classifier_bins_x_bipolar': True, 'classifier_bins_w_stochastic': False, 'classifier_bins_w_bipolar': True, 'classifier_bins_b_stochastic': True, 'classifier_bins_b_bipolar': False}. Best is trial 9 with value: 0.86012.

Trial 15 failed with error: Dimension out of range (expected to be in range of [-3, 2], but got 3)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 627, in forward
    layer_output = apply_chunking_to_forward(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/pytorch_utils.py", line 253, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 639, in feed_forward_chunk
    intermediate_output = self.intermediate(attention_output)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 539, in forward
    hidden_states = self.dense(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 448, in linearBinaryScaling
    bias = b_quantizer(bias) if bias is not None else None
           ^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 51, in binary_quantizer
    x = binarised_bipolar_op(x, 0) if bipolar else binarised_zeroScaled_op(x, 0)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
[I 2026-02-03 13:48:25,226] Trial 16 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'float32', 'bert.encoder.layer.0.attention.self.value_precision_type': 'minifloat_denorm', 'bert.encoder.layer.0.attention.self.value_mfd_width': 16, 'bert.encoder.layer.0.attention.self.value_mfd_exp_width': 5, 'bert.encoder.layer.0.attention.self.value_mfd_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_mfd_w_width': 16, 'bert.encoder.layer.0.attention.self.value_mfd_w_exp_width': 5, 'bert.encoder.layer.0.attention.self.value_mfd_w_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_mfd_b_width': 16, 'bert.encoder.layer.0.attention.self.value_mfd_b_exp_width': 4, 'bert.encoder.layer.0.attention.self.value_mfd_b_exp_bias': 7, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'binary', 'bert.encoder.layer.0.intermediate.dense_bin_w_stochastic': False, 'bert.encoder.layer.0.intermediate.dense_bin_w_bipolar': True, 'bert.encoder.layer.0.output.dense_precision_type': 'float32', 'bert.encoder.layer.1.attention.output.dense_precision_type': 'float32', 'bert.encoder.layer.1.intermediate.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.1.intermediate.dense_bins_x_stochastic': False, 'bert.encoder.layer.1.intermediate.dense_bins_x_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bins_w_stochastic': False, 'bert.encoder.layer.1.intermediate.dense_bins_w_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bins_b_stochastic': False, 'bert.encoder.layer.1.intermediate.dense_bins_b_bipolar': False, 'bert.encoder.layer.1.output.dense_precision_type': 'integer', 'bert.encoder.layer.1.output.dense_int_width': 32, 'bert.encoder.layer.1.output.dense_int_frac_width': 2, 'bert.encoder.layer.1.output.dense_weight_width': 32, 'bert.encoder.layer.1.output.dense_weight_frac_width': 8, 'bert.encoder.layer.1.output.dense_bias_width': 8, 'bert.encoder.layer.1.output.dense_bias_frac_width': 2, 'classifier_precision_type': 'integer', 'classifier_int_width': 32, 'classifier_int_frac_width': 8, 'classifier_weight_width': 32, 'classifier_weight_frac_width': 8, 'classifier_bias_width': 8, 'classifier_bias_frac_width': 4}. Best is trial 9 with value: 0.86012.

Trial 16 failed with error: Dimension out of range (expected to be in range of [-1, 0], but got 1)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 585, in forward
    self_attention_outputs = self.attention(
                             ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 515, in forward
    self_outputs = self.self(
                   ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 395, in forward
    query_layer = self.transpose_for_scores(self.query(hidden_states))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 448, in linearBinaryScaling
    bias = b_quantizer(bias) if bias is not None else None
           ^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 51, in binary_quantizer
    x = binarised_bipolar_op(x, 0) if bipolar else binarised_zeroScaled_op(x, 0)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
[I 2026-02-03 13:48:26,175] Trial 17 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'binary_scaling', 'bert.encoder.layer.0.attention.self.query_bins_x_stochastic': False, 'bert.encoder.layer.0.attention.self.query_bins_x_bipolar': True, 'bert.encoder.layer.0.attention.self.query_bins_w_stochastic': False, 'bert.encoder.layer.0.attention.self.query_bins_w_bipolar': True, 'bert.encoder.layer.0.attention.self.query_bins_b_stochastic': False, 'bert.encoder.layer.0.attention.self.query_bins_b_bipolar': False, 'bert.encoder.layer.0.attention.self.value_precision_type': 'integer', 'bert.encoder.layer.0.attention.self.value_int_width': 8, 'bert.encoder.layer.0.attention.self.value_int_frac_width': 8, 'bert.encoder.layer.0.attention.self.value_weight_width': 8, 'bert.encoder.layer.0.attention.self.value_weight_frac_width': 8, 'bert.encoder.layer.0.attention.self.value_bias_width': 8, 'bert.encoder.layer.0.attention.self.value_bias_frac_width': 4, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.0.intermediate.dense_bins_x_stochastic': False, 'bert.encoder.layer.0.intermediate.dense_bins_x_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_bins_w_stochastic': True, 'bert.encoder.layer.0.intermediate.dense_bins_w_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bins_b_stochastic': True, 'bert.encoder.layer.0.intermediate.dense_bins_b_bipolar': False, 'bert.encoder.layer.0.output.dense_precision_type': 'log', 'bert.encoder.layer.0.output.dense_log_width': 8, 'bert.encoder.layer.0.output.dense_log_exp_bias': 7, 'bert.encoder.layer.0.output.dense_log_w_width': 8, 'bert.encoder.layer.0.output.dense_log_w_exp_bias': 7, 'bert.encoder.layer.0.output.dense_log_b_width': 4, 'bert.encoder.layer.0.output.dense_log_b_exp_bias': 15, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'binary', 'bert.encoder.layer.1.attention.output.dense_bin_w_stochastic': False, 'bert.encoder.layer.1.attention.output.dense_bin_w_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'integer', 'bert.encoder.layer.1.intermediate.dense_int_width': 8, 'bert.encoder.layer.1.intermediate.dense_int_frac_width': 4, 'bert.encoder.layer.1.intermediate.dense_weight_width': 32, 'bert.encoder.layer.1.intermediate.dense_weight_frac_width': 8, 'bert.encoder.layer.1.intermediate.dense_bias_width': 8, 'bert.encoder.layer.1.intermediate.dense_bias_frac_width': 4, 'bert.encoder.layer.1.output.dense_precision_type': 'log', 'bert.encoder.layer.1.output.dense_log_width': 4, 'bert.encoder.layer.1.output.dense_log_exp_bias': 7, 'bert.encoder.layer.1.output.dense_log_w_width': 4, 'bert.encoder.layer.1.output.dense_log_w_exp_bias': 15, 'bert.encoder.layer.1.output.dense_log_b_width': 4, 'bert.encoder.layer.1.output.dense_log_b_exp_bias': 15, 'classifier_precision_type': 'binary_scaling', 'classifier_bins_x_stochastic': False, 'classifier_bins_x_bipolar': True, 'classifier_bins_w_stochastic': True, 'classifier_bins_w_bipolar': True, 'classifier_bins_b_stochastic': False, 'classifier_bins_b_bipolar': True}. Best is trial 9 with value: 0.86012.

Trial 17 failed with error: Dimension out of range (expected to be in range of [-1, 0], but got 1)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 627, in forward
    layer_output = apply_chunking_to_forward(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/pytorch_utils.py", line 253, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 640, in feed_forward_chunk
    layer_output = self.output(intermediate_output, attention_output)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 552, in forward
    hidden_states = self.dense(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 288, in forward
    return linearBinary(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 408, in linearBinary
    weight = w_quantizer(weight)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 48, in binary_quantizer
    else binarised_zeroScaled_op(x_sig, x_rand)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
[I 2026-02-03 13:48:27,120] Trial 18 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'binary', 'bert.encoder.layer.0.attention.self.query_bin_w_stochastic': True, 'bert.encoder.layer.0.attention.self.query_bin_w_bipolar': True, 'bert.encoder.layer.0.attention.self.value_precision_type': 'minifloat_denorm', 'bert.encoder.layer.0.attention.self.value_mfd_width': 8, 'bert.encoder.layer.0.attention.self.value_mfd_exp_width': 4, 'bert.encoder.layer.0.attention.self.value_mfd_exp_bias': 7, 'bert.encoder.layer.0.attention.self.value_mfd_w_width': 16, 'bert.encoder.layer.0.attention.self.value_mfd_w_exp_width': 4, 'bert.encoder.layer.0.attention.self.value_mfd_w_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_mfd_b_width': 8, 'bert.encoder.layer.0.attention.self.value_mfd_b_exp_width': 5, 'bert.encoder.layer.0.attention.self.value_mfd_b_exp_bias': 7, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'minifloat_ieee', 'bert.encoder.layer.0.intermediate.dense_mfi_width': 16, 'bert.encoder.layer.0.intermediate.dense_mfi_exp_width': 3, 'bert.encoder.layer.0.intermediate.dense_mfi_exp_bias': 15, 'bert.encoder.layer.0.intermediate.dense_mfi_w_width': 16, 'bert.encoder.layer.0.intermediate.dense_mfi_w_exp_width': 4, 'bert.encoder.layer.0.intermediate.dense_mfi_w_exp_bias': 7, 'bert.encoder.layer.0.intermediate.dense_mfi_b_width': 8, 'bert.encoder.layer.0.intermediate.dense_mfi_b_exp_width': 3, 'bert.encoder.layer.0.intermediate.dense_mfi_b_exp_bias': 15, 'bert.encoder.layer.0.output.dense_precision_type': 'binary', 'bert.encoder.layer.0.output.dense_bin_w_stochastic': True, 'bert.encoder.layer.0.output.dense_bin_w_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'integer', 'bert.encoder.layer.1.attention.output.dense_int_width': 16, 'bert.encoder.layer.1.attention.output.dense_int_frac_width': 8, 'bert.encoder.layer.1.attention.output.dense_weight_width': 8, 'bert.encoder.layer.1.attention.output.dense_weight_frac_width': 2, 'bert.encoder.layer.1.attention.output.dense_bias_width': 8, 'bert.encoder.layer.1.attention.output.dense_bias_frac_width': 4, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.1.intermediate.dense_mfd_width': 8, 'bert.encoder.layer.1.intermediate.dense_mfd_exp_width': 4, 'bert.encoder.layer.1.intermediate.dense_mfd_exp_bias': 15, 'bert.encoder.layer.1.intermediate.dense_mfd_w_width': 16, 'bert.encoder.layer.1.intermediate.dense_mfd_w_exp_width': 3, 'bert.encoder.layer.1.intermediate.dense_mfd_w_exp_bias': 7, 'bert.encoder.layer.1.intermediate.dense_mfd_b_width': 8, 'bert.encoder.layer.1.intermediate.dense_mfd_b_exp_width': 4, 'bert.encoder.layer.1.intermediate.dense_mfd_b_exp_bias': 7, 'bert.encoder.layer.1.output.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.1.output.dense_mfd_width': 8, 'bert.encoder.layer.1.output.dense_mfd_exp_width': 4, 'bert.encoder.layer.1.output.dense_mfd_exp_bias': 15, 'bert.encoder.layer.1.output.dense_mfd_w_width': 16, 'bert.encoder.layer.1.output.dense_mfd_w_exp_width': 5, 'bert.encoder.layer.1.output.dense_mfd_w_exp_bias': 15, 'bert.encoder.layer.1.output.dense_mfd_b_width': 16, 'bert.encoder.layer.1.output.dense_mfd_b_exp_width': 5, 'bert.encoder.layer.1.output.dense_mfd_b_exp_bias': 7, 'classifier_precision_type': 'binary_scaling', 'classifier_bins_x_stochastic': True, 'classifier_bins_x_bipolar': True, 'classifier_bins_w_stochastic': False, 'classifier_bins_w_bipolar': False, 'classifier_bins_b_stochastic': False, 'classifier_bins_b_bipolar': False}. Best is trial 9 with value: 0.86012.

Trial 18 failed with error: Dimension out of range (expected to be in range of [-2, 1], but got 2)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-03 13:50:36,239] Trial 19 finished with value: 0.82448 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'minifloat_ieee', 'bert.encoder.layer.0.attention.self.query_mfi_width': 16, 'bert.encoder.layer.0.attention.self.query_mfi_exp_width': 5, 'bert.encoder.layer.0.attention.self.query_mfi_exp_bias': 15, 'bert.encoder.layer.0.attention.self.query_mfi_w_width': 8, 'bert.encoder.layer.0.attention.self.query_mfi_w_exp_width': 3, 'bert.encoder.layer.0.attention.self.query_mfi_w_exp_bias': 15, 'bert.encoder.layer.0.attention.self.query_mfi_b_width': 8, 'bert.encoder.layer.0.attention.self.query_mfi_b_exp_width': 4, 'bert.encoder.layer.0.attention.self.query_mfi_b_exp_bias': 7, 'bert.encoder.layer.0.attention.self.value_precision_type': 'integer', 'bert.encoder.layer.0.attention.self.value_int_width': 16, 'bert.encoder.layer.0.attention.self.value_int_frac_width': 2, 'bert.encoder.layer.0.attention.self.value_weight_width': 8, 'bert.encoder.layer.0.attention.self.value_weight_frac_width': 8, 'bert.encoder.layer.0.attention.self.value_bias_width': 32, 'bert.encoder.layer.0.attention.self.value_bias_frac_width': 8, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'binary', 'bert.encoder.layer.0.intermediate.dense_bin_w_stochastic': True, 'bert.encoder.layer.0.intermediate.dense_bin_w_bipolar': True, 'bert.encoder.layer.0.output.dense_precision_type': 'integer', 'bert.encoder.layer.0.output.dense_int_width': 8, 'bert.encoder.layer.0.output.dense_int_frac_width': 8, 'bert.encoder.layer.0.output.dense_weight_width': 16, 'bert.encoder.layer.0.output.dense_weight_frac_width': 4, 'bert.encoder.layer.0.output.dense_bias_width': 16, 'bert.encoder.layer.0.output.dense_bias_frac_width': 8, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'float32', 'bert.encoder.layer.1.intermediate.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.1.intermediate.dense_bins_x_stochastic': False, 'bert.encoder.layer.1.intermediate.dense_bins_x_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bins_w_stochastic': True, 'bert.encoder.layer.1.intermediate.dense_bins_w_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bins_b_stochastic': True, 'bert.encoder.layer.1.intermediate.dense_bins_b_bipolar': True, 'bert.encoder.layer.1.output.dense_precision_type': 'log', 'bert.encoder.layer.1.output.dense_log_width': 8, 'bert.encoder.layer.1.output.dense_log_exp_bias': 15, 'bert.encoder.layer.1.output.dense_log_w_width': 8, 'bert.encoder.layer.1.output.dense_log_w_exp_bias': 7, 'bert.encoder.layer.1.output.dense_log_b_width': 4, 'bert.encoder.layer.1.output.dense_log_b_exp_bias': 7, 'classifier_precision_type': 'float32'}. Best is trial 9 with value: 0.86012.
/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 627, in forward
    layer_output = apply_chunking_to_forward(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/pytorch_utils.py", line 253, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 640, in feed_forward_chunk
    layer_output = self.output(intermediate_output, attention_output)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 552, in forward
    hidden_states = self.dense(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 288, in forward
    return linearBinary(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 408, in linearBinary
    weight = w_quantizer(weight)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 48, in binary_quantizer
    else binarised_zeroScaled_op(x_sig, x_rand)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
[I 2026-02-03 13:50:37,244] Trial 20 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'float32', 'bert.encoder.layer.0.attention.self.value_precision_type': 'minifloat_denorm', 'bert.encoder.layer.0.attention.self.value_mfd_width': 16, 'bert.encoder.layer.0.attention.self.value_mfd_exp_width': 4, 'bert.encoder.layer.0.attention.self.value_mfd_exp_bias': 7, 'bert.encoder.layer.0.attention.self.value_mfd_w_width': 16, 'bert.encoder.layer.0.attention.self.value_mfd_w_exp_width': 5, 'bert.encoder.layer.0.attention.self.value_mfd_w_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_mfd_b_width': 8, 'bert.encoder.layer.0.attention.self.value_mfd_b_exp_width': 3, 'bert.encoder.layer.0.attention.self.value_mfd_b_exp_bias': 15, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.0.intermediate.dense_mfd_width': 16, 'bert.encoder.layer.0.intermediate.dense_mfd_exp_width': 4, 'bert.encoder.layer.0.intermediate.dense_mfd_exp_bias': 7, 'bert.encoder.layer.0.intermediate.dense_mfd_w_width': 16, 'bert.encoder.layer.0.intermediate.dense_mfd_w_exp_width': 5, 'bert.encoder.layer.0.intermediate.dense_mfd_w_exp_bias': 15, 'bert.encoder.layer.0.intermediate.dense_mfd_b_width': 8, 'bert.encoder.layer.0.intermediate.dense_mfd_b_exp_width': 5, 'bert.encoder.layer.0.intermediate.dense_mfd_b_exp_bias': 7, 'bert.encoder.layer.0.output.dense_precision_type': 'integer', 'bert.encoder.layer.0.output.dense_int_width': 32, 'bert.encoder.layer.0.output.dense_int_frac_width': 4, 'bert.encoder.layer.0.output.dense_weight_width': 16, 'bert.encoder.layer.0.output.dense_weight_frac_width': 2, 'bert.encoder.layer.0.output.dense_bias_width': 16, 'bert.encoder.layer.0.output.dense_bias_frac_width': 8, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.1.attention.output.dense_mfd_width': 16, 'bert.encoder.layer.1.attention.output.dense_mfd_exp_width': 5, 'bert.encoder.layer.1.attention.output.dense_mfd_exp_bias': 15, 'bert.encoder.layer.1.attention.output.dense_mfd_w_width': 16, 'bert.encoder.layer.1.attention.output.dense_mfd_w_exp_width': 5, 'bert.encoder.layer.1.attention.output.dense_mfd_w_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_mfd_b_width': 16, 'bert.encoder.layer.1.attention.output.dense_mfd_b_exp_width': 5, 'bert.encoder.layer.1.attention.output.dense_mfd_b_exp_bias': 7, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'integer', 'bert.encoder.layer.1.intermediate.dense_int_width': 16, 'bert.encoder.layer.1.intermediate.dense_int_frac_width': 8, 'bert.encoder.layer.1.intermediate.dense_weight_width': 8, 'bert.encoder.layer.1.intermediate.dense_weight_frac_width': 4, 'bert.encoder.layer.1.intermediate.dense_bias_width': 16, 'bert.encoder.layer.1.intermediate.dense_bias_frac_width': 8, 'bert.encoder.layer.1.output.dense_precision_type': 'binary', 'bert.encoder.layer.1.output.dense_bin_w_stochastic': True, 'bert.encoder.layer.1.output.dense_bin_w_bipolar': False, 'classifier_precision_type': 'minifloat_ieee', 'classifier_mfi_width': 8, 'classifier_mfi_exp_width': 5, 'classifier_mfi_exp_bias': 15, 'classifier_mfi_w_width': 16, 'classifier_mfi_w_exp_width': 3, 'classifier_mfi_w_exp_bias': 15, 'classifier_mfi_b_width': 8, 'classifier_mfi_b_exp_width': 5, 'classifier_mfi_b_exp_bias': 15}. Best is trial 9 with value: 0.86012.

Trial 20 failed with error: Dimension out of range (expected to be in range of [-2, 1], but got 2)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-03 13:53:29,275] Trial 21 finished with value: 0.77788 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'float32', 'bert.encoder.layer.0.attention.self.value_precision_type': 'binary', 'bert.encoder.layer.0.attention.self.value_bin_w_stochastic': True, 'bert.encoder.layer.0.attention.self.value_bin_w_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'minifloat_ieee', 'bert.encoder.layer.0.intermediate.dense_mfi_width': 16, 'bert.encoder.layer.0.intermediate.dense_mfi_exp_width': 5, 'bert.encoder.layer.0.intermediate.dense_mfi_exp_bias': 7, 'bert.encoder.layer.0.intermediate.dense_mfi_w_width': 8, 'bert.encoder.layer.0.intermediate.dense_mfi_w_exp_width': 4, 'bert.encoder.layer.0.intermediate.dense_mfi_w_exp_bias': 7, 'bert.encoder.layer.0.intermediate.dense_mfi_b_width': 16, 'bert.encoder.layer.0.intermediate.dense_mfi_b_exp_width': 3, 'bert.encoder.layer.0.intermediate.dense_mfi_b_exp_bias': 15, 'bert.encoder.layer.0.output.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.0.output.dense_mfd_width': 16, 'bert.encoder.layer.0.output.dense_mfd_exp_width': 3, 'bert.encoder.layer.0.output.dense_mfd_exp_bias': 7, 'bert.encoder.layer.0.output.dense_mfd_w_width': 8, 'bert.encoder.layer.0.output.dense_mfd_w_exp_width': 4, 'bert.encoder.layer.0.output.dense_mfd_w_exp_bias': 15, 'bert.encoder.layer.0.output.dense_mfd_b_width': 8, 'bert.encoder.layer.0.output.dense_mfd_b_exp_width': 5, 'bert.encoder.layer.0.output.dense_mfd_b_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'integer', 'bert.encoder.layer.1.attention.output.dense_int_width': 32, 'bert.encoder.layer.1.attention.output.dense_int_frac_width': 8, 'bert.encoder.layer.1.attention.output.dense_weight_width': 8, 'bert.encoder.layer.1.attention.output.dense_weight_frac_width': 2, 'bert.encoder.layer.1.attention.output.dense_bias_width': 8, 'bert.encoder.layer.1.attention.output.dense_bias_frac_width': 8, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'log', 'bert.encoder.layer.1.intermediate.dense_log_width': 8, 'bert.encoder.layer.1.intermediate.dense_log_exp_bias': 7, 'bert.encoder.layer.1.intermediate.dense_log_w_width': 8, 'bert.encoder.layer.1.intermediate.dense_log_w_exp_bias': 15, 'bert.encoder.layer.1.intermediate.dense_log_b_width': 4, 'bert.encoder.layer.1.intermediate.dense_log_b_exp_bias': 15, 'bert.encoder.layer.1.output.dense_precision_type': 'float32', 'classifier_precision_type': 'minifloat_ieee', 'classifier_mfi_width': 8, 'classifier_mfi_exp_width': 4, 'classifier_mfi_exp_bias': 7, 'classifier_mfi_w_width': 8, 'classifier_mfi_w_exp_width': 4, 'classifier_mfi_w_exp_bias': 7, 'classifier_mfi_b_width': 8, 'classifier_mfi_b_exp_width': 3, 'classifier_mfi_b_exp_bias': 15}. Best is trial 9 with value: 0.86012.
/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 627, in forward
    layer_output = apply_chunking_to_forward(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/pytorch_utils.py", line 253, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 639, in feed_forward_chunk
    intermediate_output = self.intermediate(attention_output)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 539, in forward
    hidden_states = self.dense(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 446, in linearBinaryScaling
    x = x_quantizer(x)
        ^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 51, in binary_quantizer
    x = binarised_bipolar_op(x, 0) if bipolar else binarised_zeroScaled_op(x, 0)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
[I 2026-02-03 13:53:30,217] Trial 22 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'minifloat_denorm', 'bert.encoder.layer.0.attention.self.query_mfd_width': 16, 'bert.encoder.layer.0.attention.self.query_mfd_exp_width': 4, 'bert.encoder.layer.0.attention.self.query_mfd_exp_bias': 7, 'bert.encoder.layer.0.attention.self.query_mfd_w_width': 8, 'bert.encoder.layer.0.attention.self.query_mfd_w_exp_width': 3, 'bert.encoder.layer.0.attention.self.query_mfd_w_exp_bias': 15, 'bert.encoder.layer.0.attention.self.query_mfd_b_width': 16, 'bert.encoder.layer.0.attention.self.query_mfd_b_exp_width': 5, 'bert.encoder.layer.0.attention.self.query_mfd_b_exp_bias': 7, 'bert.encoder.layer.0.attention.self.value_precision_type': 'float32', 'bert.encoder.layer.0.intermediate.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.0.intermediate.dense_bins_x_stochastic': False, 'bert.encoder.layer.0.intermediate.dense_bins_x_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_bins_w_stochastic': False, 'bert.encoder.layer.0.intermediate.dense_bins_w_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bins_b_stochastic': False, 'bert.encoder.layer.0.intermediate.dense_bins_b_bipolar': False, 'bert.encoder.layer.0.output.dense_precision_type': 'integer', 'bert.encoder.layer.0.output.dense_int_width': 16, 'bert.encoder.layer.0.output.dense_int_frac_width': 4, 'bert.encoder.layer.0.output.dense_weight_width': 8, 'bert.encoder.layer.0.output.dense_weight_frac_width': 4, 'bert.encoder.layer.0.output.dense_bias_width': 16, 'bert.encoder.layer.0.output.dense_bias_frac_width': 2, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'integer', 'bert.encoder.layer.1.attention.output.dense_int_width': 8, 'bert.encoder.layer.1.attention.output.dense_int_frac_width': 2, 'bert.encoder.layer.1.attention.output.dense_weight_width': 16, 'bert.encoder.layer.1.attention.output.dense_weight_frac_width': 4, 'bert.encoder.layer.1.attention.output.dense_bias_width': 16, 'bert.encoder.layer.1.attention.output.dense_bias_frac_width': 4, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'binary', 'bert.encoder.layer.1.intermediate.dense_bin_w_stochastic': True, 'bert.encoder.layer.1.intermediate.dense_bin_w_bipolar': False, 'bert.encoder.layer.1.output.dense_precision_type': 'integer', 'bert.encoder.layer.1.output.dense_int_width': 16, 'bert.encoder.layer.1.output.dense_int_frac_width': 8, 'bert.encoder.layer.1.output.dense_weight_width': 32, 'bert.encoder.layer.1.output.dense_weight_frac_width': 2, 'bert.encoder.layer.1.output.dense_bias_width': 32, 'bert.encoder.layer.1.output.dense_bias_frac_width': 2, 'classifier_precision_type': 'binary_scaling', 'classifier_bins_x_stochastic': True, 'classifier_bins_x_bipolar': False, 'classifier_bins_w_stochastic': True, 'classifier_bins_w_bipolar': False, 'classifier_bins_b_stochastic': True, 'classifier_bins_b_bipolar': False}. Best is trial 9 with value: 0.86012.

Trial 22 failed with error: Dimension out of range (expected to be in range of [-3, 2], but got 3)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 627, in forward
    layer_output = apply_chunking_to_forward(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/pytorch_utils.py", line 253, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 639, in feed_forward_chunk
    intermediate_output = self.intermediate(attention_output)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 539, in forward
    hidden_states = self.dense(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 446, in linearBinaryScaling
    x = x_quantizer(x)
        ^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 48, in binary_quantizer
    else binarised_zeroScaled_op(x_sig, x_rand)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
[I 2026-02-03 13:53:31,109] Trial 23 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'log', 'bert.encoder.layer.0.attention.self.query_log_width': 4, 'bert.encoder.layer.0.attention.self.query_log_exp_bias': 7, 'bert.encoder.layer.0.attention.self.query_log_w_width': 4, 'bert.encoder.layer.0.attention.self.query_log_w_exp_bias': 15, 'bert.encoder.layer.0.attention.self.query_log_b_width': 4, 'bert.encoder.layer.0.attention.self.query_log_b_exp_bias': 15, 'bert.encoder.layer.0.attention.self.value_precision_type': 'integer', 'bert.encoder.layer.0.attention.self.value_int_width': 32, 'bert.encoder.layer.0.attention.self.value_int_frac_width': 4, 'bert.encoder.layer.0.attention.self.value_weight_width': 16, 'bert.encoder.layer.0.attention.self.value_weight_frac_width': 2, 'bert.encoder.layer.0.attention.self.value_bias_width': 32, 'bert.encoder.layer.0.attention.self.value_bias_frac_width': 8, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'binary', 'bert.encoder.layer.0.intermediate.dense_bin_w_stochastic': False, 'bert.encoder.layer.0.intermediate.dense_bin_w_bipolar': True, 'bert.encoder.layer.0.output.dense_precision_type': 'log', 'bert.encoder.layer.0.output.dense_log_width': 4, 'bert.encoder.layer.0.output.dense_log_exp_bias': 7, 'bert.encoder.layer.0.output.dense_log_w_width': 8, 'bert.encoder.layer.0.output.dense_log_w_exp_bias': 7, 'bert.encoder.layer.0.output.dense_log_b_width': 8, 'bert.encoder.layer.0.output.dense_log_b_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'log', 'bert.encoder.layer.1.attention.output.dense_log_width': 4, 'bert.encoder.layer.1.attention.output.dense_log_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_log_w_width': 8, 'bert.encoder.layer.1.attention.output.dense_log_w_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_log_b_width': 8, 'bert.encoder.layer.1.attention.output.dense_log_b_exp_bias': 7, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.1.intermediate.dense_bins_x_stochastic': True, 'bert.encoder.layer.1.intermediate.dense_bins_x_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bins_w_stochastic': True, 'bert.encoder.layer.1.intermediate.dense_bins_w_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bins_b_stochastic': True, 'bert.encoder.layer.1.intermediate.dense_bins_b_bipolar': False, 'bert.encoder.layer.1.output.dense_precision_type': 'integer', 'bert.encoder.layer.1.output.dense_int_width': 8, 'bert.encoder.layer.1.output.dense_int_frac_width': 8, 'bert.encoder.layer.1.output.dense_weight_width': 16, 'bert.encoder.layer.1.output.dense_weight_frac_width': 4, 'bert.encoder.layer.1.output.dense_bias_width': 16, 'bert.encoder.layer.1.output.dense_bias_frac_width': 8, 'classifier_precision_type': 'binary', 'classifier_bin_w_stochastic': False, 'classifier_bin_w_bipolar': True}. Best is trial 9 with value: 0.86012.

Trial 23 failed with error: Dimension out of range (expected to be in range of [-3, 2], but got 3)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 627, in forward
    layer_output = apply_chunking_to_forward(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/pytorch_utils.py", line 253, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 639, in feed_forward_chunk
    intermediate_output = self.intermediate(attention_output)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 539, in forward
    hidden_states = self.dense(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 288, in forward
    return linearBinary(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 408, in linearBinary
    weight = w_quantizer(weight)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 51, in binary_quantizer
    x = binarised_bipolar_op(x, 0) if bipolar else binarised_zeroScaled_op(x, 0)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
[I 2026-02-03 13:53:32,022] Trial 24 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'binary', 'bert.encoder.layer.0.attention.self.query_bin_w_stochastic': True, 'bert.encoder.layer.0.attention.self.query_bin_w_bipolar': True, 'bert.encoder.layer.0.attention.self.value_precision_type': 'minifloat_ieee', 'bert.encoder.layer.0.attention.self.value_mfi_width': 16, 'bert.encoder.layer.0.attention.self.value_mfi_exp_width': 3, 'bert.encoder.layer.0.attention.self.value_mfi_exp_bias': 7, 'bert.encoder.layer.0.attention.self.value_mfi_w_width': 16, 'bert.encoder.layer.0.attention.self.value_mfi_w_exp_width': 4, 'bert.encoder.layer.0.attention.self.value_mfi_w_exp_bias': 7, 'bert.encoder.layer.0.attention.self.value_mfi_b_width': 8, 'bert.encoder.layer.0.attention.self.value_mfi_b_exp_width': 3, 'bert.encoder.layer.0.attention.self.value_mfi_b_exp_bias': 15, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'binary', 'bert.encoder.layer.0.intermediate.dense_bin_w_stochastic': False, 'bert.encoder.layer.0.intermediate.dense_bin_w_bipolar': False, 'bert.encoder.layer.0.output.dense_precision_type': 'log', 'bert.encoder.layer.0.output.dense_log_width': 8, 'bert.encoder.layer.0.output.dense_log_exp_bias': 15, 'bert.encoder.layer.0.output.dense_log_w_width': 8, 'bert.encoder.layer.0.output.dense_log_w_exp_bias': 15, 'bert.encoder.layer.0.output.dense_log_b_width': 8, 'bert.encoder.layer.0.output.dense_log_b_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'binary', 'bert.encoder.layer.1.attention.output.dense_bin_w_stochastic': False, 'bert.encoder.layer.1.attention.output.dense_bin_w_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'float32', 'bert.encoder.layer.1.output.dense_precision_type': 'integer', 'bert.encoder.layer.1.output.dense_int_width': 8, 'bert.encoder.layer.1.output.dense_int_frac_width': 8, 'bert.encoder.layer.1.output.dense_weight_width': 8, 'bert.encoder.layer.1.output.dense_weight_frac_width': 8, 'bert.encoder.layer.1.output.dense_bias_width': 16, 'bert.encoder.layer.1.output.dense_bias_frac_width': 2, 'classifier_precision_type': 'integer', 'classifier_int_width': 8, 'classifier_int_frac_width': 4, 'classifier_weight_width': 8, 'classifier_weight_frac_width': 2, 'classifier_bias_width': 16, 'classifier_bias_frac_width': 4}. Best is trial 9 with value: 0.86012.

Trial 24 failed with error: Dimension out of range (expected to be in range of [-2, 1], but got 2)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-03 13:55:02,944] Trial 25 finished with value: 0.8452 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'integer', 'bert.encoder.layer.0.attention.self.query_int_width': 32, 'bert.encoder.layer.0.attention.self.query_int_frac_width': 2, 'bert.encoder.layer.0.attention.self.query_weight_width': 8, 'bert.encoder.layer.0.attention.self.query_weight_frac_width': 2, 'bert.encoder.layer.0.attention.self.query_bias_width': 32, 'bert.encoder.layer.0.attention.self.query_bias_frac_width': 4, 'bert.encoder.layer.0.attention.self.value_precision_type': 'integer', 'bert.encoder.layer.0.attention.self.value_int_width': 16, 'bert.encoder.layer.0.attention.self.value_int_frac_width': 2, 'bert.encoder.layer.0.attention.self.value_weight_width': 8, 'bert.encoder.layer.0.attention.self.value_weight_frac_width': 4, 'bert.encoder.layer.0.attention.self.value_bias_width': 16, 'bert.encoder.layer.0.attention.self.value_bias_frac_width': 2, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'float32', 'bert.encoder.layer.0.output.dense_precision_type': 'log', 'bert.encoder.layer.0.output.dense_log_width': 8, 'bert.encoder.layer.0.output.dense_log_exp_bias': 7, 'bert.encoder.layer.0.output.dense_log_w_width': 4, 'bert.encoder.layer.0.output.dense_log_w_exp_bias': 7, 'bert.encoder.layer.0.output.dense_log_b_width': 8, 'bert.encoder.layer.0.output.dense_log_b_exp_bias': 15, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'float32', 'bert.encoder.layer.1.intermediate.dense_precision_type': 'binary', 'bert.encoder.layer.1.intermediate.dense_bin_w_stochastic': False, 'bert.encoder.layer.1.intermediate.dense_bin_w_bipolar': True, 'bert.encoder.layer.1.output.dense_precision_type': 'binary', 'bert.encoder.layer.1.output.dense_bin_w_stochastic': True, 'bert.encoder.layer.1.output.dense_bin_w_bipolar': True, 'classifier_precision_type': 'integer', 'classifier_int_width': 32, 'classifier_int_frac_width': 2, 'classifier_weight_width': 16, 'classifier_weight_frac_width': 4, 'classifier_bias_width': 32, 'classifier_bias_frac_width': 8}. Best is trial 9 with value: 0.86012.
/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 585, in forward
    self_attention_outputs = self.attention(
                             ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 524, in forward
    attention_output = self.output(self_outputs[0], hidden_states)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 466, in forward
    hidden_states = self.dense(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 446, in linearBinaryScaling
    x = x_quantizer(x)
        ^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 48, in binary_quantizer
    else binarised_zeroScaled_op(x_sig, x_rand)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
[I 2026-02-03 13:55:03,835] Trial 26 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'minifloat_denorm', 'bert.encoder.layer.0.attention.self.query_mfd_width': 8, 'bert.encoder.layer.0.attention.self.query_mfd_exp_width': 4, 'bert.encoder.layer.0.attention.self.query_mfd_exp_bias': 7, 'bert.encoder.layer.0.attention.self.query_mfd_w_width': 8, 'bert.encoder.layer.0.attention.self.query_mfd_w_exp_width': 4, 'bert.encoder.layer.0.attention.self.query_mfd_w_exp_bias': 15, 'bert.encoder.layer.0.attention.self.query_mfd_b_width': 8, 'bert.encoder.layer.0.attention.self.query_mfd_b_exp_width': 4, 'bert.encoder.layer.0.attention.self.query_mfd_b_exp_bias': 7, 'bert.encoder.layer.0.attention.self.value_precision_type': 'integer', 'bert.encoder.layer.0.attention.self.value_int_width': 8, 'bert.encoder.layer.0.attention.self.value_int_frac_width': 2, 'bert.encoder.layer.0.attention.self.value_weight_width': 16, 'bert.encoder.layer.0.attention.self.value_weight_frac_width': 2, 'bert.encoder.layer.0.attention.self.value_bias_width': 32, 'bert.encoder.layer.0.attention.self.value_bias_frac_width': 8, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'log', 'bert.encoder.layer.0.intermediate.dense_log_width': 8, 'bert.encoder.layer.0.intermediate.dense_log_exp_bias': 7, 'bert.encoder.layer.0.intermediate.dense_log_w_width': 4, 'bert.encoder.layer.0.intermediate.dense_log_w_exp_bias': 15, 'bert.encoder.layer.0.intermediate.dense_log_b_width': 8, 'bert.encoder.layer.0.intermediate.dense_log_b_exp_bias': 7, 'bert.encoder.layer.0.output.dense_precision_type': 'float32', 'bert.encoder.layer.1.attention.output.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.1.attention.output.dense_bins_x_stochastic': True, 'bert.encoder.layer.1.attention.output.dense_bins_x_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bins_w_stochastic': False, 'bert.encoder.layer.1.attention.output.dense_bins_w_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bins_b_stochastic': True, 'bert.encoder.layer.1.attention.output.dense_bins_b_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'integer', 'bert.encoder.layer.1.intermediate.dense_int_width': 16, 'bert.encoder.layer.1.intermediate.dense_int_frac_width': 8, 'bert.encoder.layer.1.intermediate.dense_weight_width': 16, 'bert.encoder.layer.1.intermediate.dense_weight_frac_width': 2, 'bert.encoder.layer.1.intermediate.dense_bias_width': 16, 'bert.encoder.layer.1.intermediate.dense_bias_frac_width': 2, 'bert.encoder.layer.1.output.dense_precision_type': 'log', 'bert.encoder.layer.1.output.dense_log_width': 8, 'bert.encoder.layer.1.output.dense_log_exp_bias': 15, 'bert.encoder.layer.1.output.dense_log_w_width': 8, 'bert.encoder.layer.1.output.dense_log_w_exp_bias': 15, 'bert.encoder.layer.1.output.dense_log_b_width': 8, 'bert.encoder.layer.1.output.dense_log_b_exp_bias': 7, 'classifier_precision_type': 'float32'}. Best is trial 9 with value: 0.86012.

Trial 26 failed with error: Dimension out of range (expected to be in range of [-3, 2], but got 3)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Traceback (most recent call last):
  File "/tmp/ipykernel_412256/3199720232.py", line 18, in objective
    trainer.train()
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1675, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1144, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 585, in forward
    self_attention_outputs = self.attention(
                             ^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 524, in forward
    attention_output = self.output(self_outputs[0], hidden_states)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 466, in forward
    hidden_states = self.dense(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/modules/linear.py", line 321, in forward
    return linearBinaryScaling(x, self.weight, self.bias, self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantized/functional/linear.py", line 446, in linearBinaryScaling
    x = x_quantizer(x)
        ^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/binary.py", line 48, in binary_quantizer
    else binarised_zeroScaled_op(x_sig, x_rand)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 163, in forward
    alpha = BinaryZeroScaled.alpha(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ism/ADL/mase/src/chop/nn/quantizers/utils.py", line 158, in alpha
    alpha = absvalue.mean(dim=(1, 2, 3), keepdims=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
[I 2026-02-03 13:55:04,735] Trial 27 finished with value: 0.0 and parameters: {'bert.encoder.layer.0.attention.self.query_precision_type': 'float32', 'bert.encoder.layer.0.attention.self.value_precision_type': 'integer', 'bert.encoder.layer.0.attention.self.value_int_width': 16, 'bert.encoder.layer.0.attention.self.value_int_frac_width': 8, 'bert.encoder.layer.0.attention.self.value_weight_width': 16, 'bert.encoder.layer.0.attention.self.value_weight_frac_width': 8, 'bert.encoder.layer.0.attention.self.value_bias_width': 32, 'bert.encoder.layer.0.attention.self.value_bias_frac_width': 2, 'bert.encoder.layer.0.intermediate.dense_precision_type': 'float32', 'bert.encoder.layer.0.output.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.0.output.dense_mfd_width': 8, 'bert.encoder.layer.0.output.dense_mfd_exp_width': 3, 'bert.encoder.layer.0.output.dense_mfd_exp_bias': 15, 'bert.encoder.layer.0.output.dense_mfd_w_width': 8, 'bert.encoder.layer.0.output.dense_mfd_w_exp_width': 5, 'bert.encoder.layer.0.output.dense_mfd_w_exp_bias': 7, 'bert.encoder.layer.0.output.dense_mfd_b_width': 8, 'bert.encoder.layer.0.output.dense_mfd_b_exp_width': 3, 'bert.encoder.layer.0.output.dense_mfd_b_exp_bias': 7, 'bert.encoder.layer.1.attention.output.dense_precision_type': 'binary_scaling', 'bert.encoder.layer.1.attention.output.dense_bins_x_stochastic': True, 'bert.encoder.layer.1.attention.output.dense_bins_x_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bins_w_stochastic': False, 'bert.encoder.layer.1.attention.output.dense_bins_w_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bins_b_stochastic': True, 'bert.encoder.layer.1.attention.output.dense_bins_b_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_precision_type': 'log', 'bert.encoder.layer.1.intermediate.dense_log_width': 8, 'bert.encoder.layer.1.intermediate.dense_log_exp_bias': 7, 'bert.encoder.layer.1.intermediate.dense_log_w_width': 4, 'bert.encoder.layer.1.intermediate.dense_log_w_exp_bias': 15, 'bert.encoder.layer.1.intermediate.dense_log_b_width': 4, 'bert.encoder.layer.1.intermediate.dense_log_b_exp_bias': 15, 'bert.encoder.layer.1.output.dense_precision_type': 'minifloat_denorm', 'bert.encoder.layer.1.output.dense_mfd_width': 8, 'bert.encoder.layer.1.output.dense_mfd_exp_width': 5, 'bert.encoder.layer.1.output.dense_mfd_exp_bias': 15, 'bert.encoder.layer.1.output.dense_mfd_w_width': 16, 'bert.encoder.layer.1.output.dense_mfd_w_exp_width': 4, 'bert.encoder.layer.1.output.dense_mfd_w_exp_bias': 15, 'bert.encoder.layer.1.output.dense_mfd_b_width': 8, 'bert.encoder.layer.1.output.dense_mfd_b_exp_width': 5, 'bert.encoder.layer.1.output.dense_mfd_b_exp_bias': 7, 'classifier_precision_type': 'binary_scaling', 'classifier_bins_x_stochastic': True, 'classifier_bins_x_bipolar': False, 'classifier_bins_w_stochastic': True, 'classifier_bins_w_bipolar': True, 'classifier_bins_b_stochastic': False, 'classifier_bins_b_bipolar': True}. Best is trial 9 with value: 0.86012.

Trial 27 failed with error: Dimension out of range (expected to be in range of [-3, 2], but got 3)

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
# ============================================================================
# ANALYZE RESULTS BY PRECISION TYPE
# ============================================================================

import pandas as pd
from collections import defaultdict

# Group trials by precision type
precision_performance = defaultdict(list)

for trial in study.trials:
    if trial.value is not None and trial.value > 0:
        # Extract precision type from trial params
        precision_type = None
        for param_name in trial.params:
            if param_name.endswith('_precision_type'):
                precision_type = trial.params[param_name]
                break
        
        if precision_type:
            precision_performance[precision_type].append({
                'trial_number': trial.number,
                'accuracy': trial.value,
                'params': trial.params
            })

# Create summary statistics
summary_data = []
for precision_type, trials in precision_performance.items():
    accuracies = [t['accuracy'] for t in trials]
    summary_data.append({
        'Precision Type': precision_type,
        'Count': len(accuracies),
        'Best Accuracy': f"{max(accuracies):.4f}",
        'Mean Accuracy': f"{sum(accuracies)/len(accuracies):.4f}",
        'Worst Accuracy': f"{min(accuracies):.4f}",
    })

summary_df = pd.DataFrame(summary_data)
summary_df = summary_df.sort_values('Best Accuracy', ascending=False)

print("=" * 80)
print("PRECISION TYPE PERFORMANCE SUMMARY")
print("=" * 80)
print(summary_df.to_string(index=False))
print("=" * 80)

In [ ]:
# ============================================================================
# VISUALIZE: CUMULATIVE MAX ACCURACY VS TRIAL NUMBER
# ============================================================================

import matplotlib.pyplot as plt
import numpy as np

# Get trial data
trial_numbers = []
trial_accuracies = []
cumulative_max = []

current_max = 0
for trial in study.trials:
    if trial.value is not None:
        trial_numbers.append(trial.number)
        trial_accuracies.append(trial.value)
        current_max = max(current_max, trial.value)
        cumulative_max.append(current_max)

# Create the plot
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# Plot 1: Cumulative Max Accuracy
ax1.plot(trial_numbers, cumulative_max, marker='o', linewidth=2, markersize=4, color='blue', alpha=0.7)
ax1.set_xlabel('Trial Number', fontsize=12)
ax1.set_ylabel('Maximum Achieved Accuracy', fontsize=12)
ax1.set_title('Cumulative Maximum Accuracy Over Trials', fontsize=14, fontweight='bold')
ax1.grid(True, alpha=0.3)

# Plot 2: All trial accuracies with color by precision type
precision_colors = {
    'float32': 'red',
    'integer': 'blue',
    'minifloat_denorm': 'green',
    'minifloat_ieee': 'orange',
    'log': 'purple',
    'binary': 'brown',
    'binary_scaling': 'pink',
}

for precision_type, color in precision_colors.items():
    if precision_type in precision_performance:
        trials_data = precision_performance[precision_type]
        x = [t['trial_number'] for t in trials_data]
        y = [t['accuracy'] for t in trials_data]
        ax2.scatter(x, y, label=precision_type, color=color, alpha=0.6, s=50)

ax2.set_xlabel('Trial Number', fontsize=12)
ax2.set_ylabel('Accuracy', fontsize=12)
ax2.set_title('Trial Accuracies by Precision Type', fontsize=14, fontweight='bold')
ax2.legend(loc='best', fontsize=9)
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('precision_search_results.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"\n✓ Figure saved to 'precision_search_results.png'")